CREATE TABLE IF NOT EXISTS judge_sessions (
 id TEXT PRIMARY KEY, created_at INTEGER NOT NULL, expires_at INTEGER NOT NULL,
 actions INTEGER NOT NULL DEFAULT 0, analyses INTEGER NOT NULL DEFAULT 0,
 resets INTEGER NOT NULL DEFAULT 0
);
