import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {prepareCollector,collectAnonymous,trackingStatus,collectorEndpoint} from '../lib/pixel-collector.ts';
const shop='demo-store.myshopify.com',time=new Date('2026-10-09T12:00:00Z');
function fixture(){const sql=new DatabaseSync(':memory:');for(const file of readdirSync(new URL('../drizzle/',import.meta.url)).filter(f=>/^\d{4}.*\.sql$/.test(f)).sort())sql.exec(readFileSync(new URL(`../drizzle/${file}`,import.meta.url),'utf8'));function prepare(query,params=[]){return {bind(...args){return prepare(query,args)},async first(){return sql.prepare(query).get(...params)||null},async all(){return {results:sql.prepare(query).all(...params)}},async run(){return {meta:{changes:Number(sql.prepare(query).run(...params).changes)}}}}}return {sql,db:{prepare}}}
const event={id:'view-1',kind:'product_viewed',at:time.toISOString(),analyticsAllowed:true,marketingAllowed:true,clientId:'browser-identifier',product:'Trail Shoes'};
test('public collector stays anonymous, hashes browser identifiers, and deduplicates receipts',async()=>{const {db,sql}=fixture();const settings=await prepareCollector(db,shop,'https://resolve.example',()=>time),key=new URL(settings.endpointUrl).searchParams.get('key');await collectAnonymous(db,shop,key,event,()=>time);await collectAnonymous(db,shop,key,event,()=>time);const row=sql.prepare('SELECT client_id,identity_basis FROM shopping_events').get();assert.equal(row.identity_basis,'anonymous');assert.match(row.client_id,/^[a-f0-9]{64}$/);assert.notEqual(row.client_id,event.clientId);assert.equal(sql.prepare('SELECT count(*) n FROM shopping_events').get().n,1);assert.equal(sql.prepare('SELECT count(*) n FROM retention_accounts').get().n,0);const status=await trackingStatus(db,shop);assert.equal(status.collectorPrepared,true);assert.equal(status.registrationVerified,false);assert.equal(status.eventCounts[0].events,1)});
test('forged identity, withdrawn consent, stale events and invalid routing cannot create records',async()=>{const {db,sql}=fixture(),settings=await prepareCollector(db,shop,'https://resolve.example',()=>time),key=new URL(settings.endpointUrl).searchParams.get('key');for(const bad of [{...event,customerId:'123'},{...event,marketingAllowed:false},{...event,analyticsAllowed:false},{...event,at:'2026-10-01T12:00:00Z'}])await assert.rejects(()=>collectAnonymous(db,shop,key,bad,()=>time));await assert.rejects(()=>collectAnonymous(db,shop,'a'.repeat(64),event,()=>time));assert.equal(sql.prepare('SELECT count(*) n FROM shopping_events').get().n,0)});
test('disabled and exhausted collectors reject new events',async()=>{const {db,sql}=fixture(),settings=await prepareCollector(db,shop,'https://resolve.example',()=>time),key=new URL(settings.endpointUrl).searchParams.get('key');sql.prepare('UPDATE pixel_collectors SET quota_day=?,quota_count=10000 WHERE shop=?').run('2026-10-09',shop);await assert.rejects(()=>collectAnonymous(db,shop,key,event,()=>time),error=>error.status===429);sql.prepare('UPDATE pixel_collectors SET enabled=0 WHERE shop=?').run(shop);await assert.rejects(()=>prepareCollector(db,shop,'https://resolve.example',()=>time),error=>error.status===403)});
test('collector destination requires the independent app HTTPS origin',()=>{for(const value of ['http://resolve.example',`https://${shop}`,'https://user:secret@resolve.example','https://resolve.example?token=x'])assert.throws(()=>collectorEndpoint(value,shop));assert.equal(collectorEndpoint('https://resolve.example',shop),'https://resolve.example/api/pixel/collect')});
