import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {scoreRisk,baselineDiagnosis,validateDiagnosis,outreachBlock,defaultPolicy} from '../lib/retention-core.ts';
import {demoSeed} from '../lib/retention-seed.ts';
import {retentionStore} from '../lib/retention-store.ts';
const clock=new Date('2026-10-09T10:00:00.000Z');
// Runs the actual repository SQL against SQLite; provider calls are injected mocks.
function fixture(options={}){
 const sqlite=new DatabaseSync(':memory:');
 for(const file of ['0000_unique_paibok.sql','0001_confused_captain_cross.sql','0002_open_expediter.sql','0003_retention_workflow.sql'])sqlite.exec(readFileSync(new URL(`../drizzle/${file}`,import.meta.url),'utf8'));
 function statement(sql,values=[]){return {sql,values,bind(...v){return statement(sql,v)},async first(){return sqlite.prepare(sql).get(...values)||null},async all(){return {results:sqlite.prepare(sql).all(...values)}},async run(){const r=sqlite.prepare(sql).run(...values);return {meta:{changes:Number(r.changes)}}}}}
 const db={prepare:statement,async batch(items){sqlite.exec('BEGIN');try{const results=[];for(const item of items)results.push(await item.run());sqlite.exec('COMMIT');return results}catch(e){sqlite.exec('ROLLBACK');throw e}}};
 const store=retentionStore({db,now:()=>clock,...options});return {store,sqlite};
}
const northstar=demoSeed(clock)[0];
function diagnosis(p){return {...baselineDiagnosis(p.account,p.events,p.actions,clock,p.policy),engine:'gemini',model:'mock-test-model'};}
function withoutMeta(d){const {engine,model,...rest}=d;return rest;}

test('risk has a reproducible 90-point breakdown backed by actual events',()=>{const r=scoreRisk(northstar.events);assert.equal(r.score,90);assert.equal(r.level,'High');assert.equal(r.evidence.reduce((n,e)=>n+e.points,0),90);for(const e of r.evidence)assert(northstar.events.some(v=>v.id===e.eventId));});
test('empty activity is unknown, not a fabricated healthy customer',()=>{const r=scoreRisk([]);assert.equal(r.score,0);assert.equal(r.level,'Unknown');assert.equal(r.evidence.length,0);});
test('order cancellation does not establish churn or a specific cause',()=>{const r=scoreRisk([{id:'order',kind:'order_cancelled',at:clock.toISOString(),summary:'Cancelled',data:{},synthetic:false}]);assert.equal(r.score,10);assert.match(r.evidence[0].label,/unknown/);});
test('restored integration overrides older failures but not later failures',()=>{const restored={id:'restore',kind:'integration_restored',at:clock.toISOString(),summary:'Restored',data:{},synthetic:true};assert.equal(scoreRisk([...northstar.events,restored]).score,45);assert.equal(scoreRisk([...northstar.events,restored,{...northstar.events[0],id:'new-failure',at:new Date(clock.getTime()+1000).toISOString()}]).score,80);});
test('usage drop without a numeric decline does not invent points',()=>{assert.equal(scoreRisk([{id:'u',kind:'usage_drop',at:clock.toISOString(),summary:'Unknown change',data:{},synthetic:true}]).score,0);});
test('risk weights are capped at 100 and old repeated failures do not multiply base weight',()=>{assert.equal(scoreRisk([...northstar.events,{...northstar.events[0],id:'extra'},{...northstar.events[0],id:'billing',kind:'payment_failed'}]).score,100);});
test('integration problems select troubleshooting rather than incentives',()=>{const d=baselineDiagnosis(northstar.account,northstar.events,[],clock,defaultPolicy);assert.equal(d.action,'troubleshoot');assert.match(d.message,/Northstar/);assert.doesNotMatch(d.message,/discount/i);});
test('onboarding, payment, healthy and opted-out scenarios choose appropriate actions',()=>{const seed=demoSeed(clock),expected=['troubleshoot','onboarding_help','no_action','internal_review','onboarding_help','billing_help'];seed.forEach((s,i)=>assert.equal(baselineDiagnosis(s.account,s.events,[],clock,defaultPolicy).action,expected[i]));});
test('communication permission missing suppresses email',()=>{const a={...northstar.account,profile:{...northstar.account.profile,emailConsent:'unknown'}};assert.equal(baselineDiagnosis(a,northstar.events,[],clock,defaultPolicy).action,'no_action');});
test('AI cannot cite nonexistent evidence, choose an unrelated intervention, or send to opted-out customer',()=>{const d=withoutMeta(baselineDiagnosis(northstar.account,northstar.events,[],clock,defaultPolicy));assert.throws(()=>validateDiagnosis({...d,evidenceIds:['invented']},northstar.account,northstar.events,[],clock,defaultPolicy));assert.throws(()=>validateDiagnosis({...d,action:'billing_help'},northstar.account,northstar.events,[],clock,defaultPolicy));const opted={...northstar.account,profile:{...northstar.account.profile,emailConsent:'opted_out'}};assert.throws(()=>validateDiagnosis(d,opted,northstar.events,[],clock,defaultPolicy));});
test('AI schema rejects extra fields and an email without evidence',()=>{const d=withoutMeta(baselineDiagnosis(northstar.account,northstar.events,[],clock,defaultPolicy));assert.throws(()=>validateDiagnosis({...d,discount:50},northstar.account,northstar.events,[],clock,defaultPolicy));assert.throws(()=>validateDiagnosis({...d,evidenceIds:[]},northstar.account,northstar.events,[],clock,defaultPolicy));});
test('no action always clears email content',()=>{const d=withoutMeta(baselineDiagnosis(northstar.account,northstar.events,[],clock,defaultPolicy));const v=validateDiagnosis({...d,action:'no_action'},northstar.account,northstar.events,[],clock,defaultPolicy);assert.equal(v.message,'');assert.equal(v.subject,'');});
test('complete persisted workflow: evidence → AI → approval → simulated delivery → re-engagement → risk recalculation',async()=>{
 let calls=0;const {store}=fixture({ai:async p=>{calls++;return diagnosis(p)}});await store.seed();let p=await store.profile('demo:northstar');assert.equal(p.risk.score,90);assert.equal(p.events.length,5);
 p=await store.analyze(p.account.id,p.account.version);assert.equal(calls,1);assert.equal(p.decision.diagnosis.engine,'gemini');assert.equal(p.actions.length,0,'Manual approval must remain default');
 p=await store.execute(p.account.id,p.account.version);assert.equal(p.actions[0].status,'simulated');assert.equal(p.actions[0].approvedBy,'operator');assert.equal(p.actions[0].providerId,null);assert.equal(p.risk.score,90,'Sending alone does not improve risk');
 p=await store.reengage(p.account.id,p.account.version);assert.equal(p.risk.score,0);assert.equal(p.baseline,90);assert.equal(p.events.length,8);assert(p.events.slice(-3).every(e=>e.synthetic));assert(p.audit.some(a=>a.kind==='approved'));assert(p.audit.some(a=>a.kind==='simulated_activity'));
 const again=await store.profile(p.account.id);assert.equal(again.risk.score,0);assert.equal(again.actions.length,1);assert.equal(again.events.length,8);
});
test('approval before analysis and outcome before execution are rejected',async()=>{const {store}=fixture();await store.seed();const p=await store.profile('demo:northstar');await assert.rejects(store.execute(p.account.id,p.account.version),/Analyze/);await assert.rejects(store.reengage(p.account.id,p.account.version),/Execute/);});
test('duplicate approval cannot execute the same intervention twice',async()=>{const {store}=fixture();await store.seed();let p=await store.profile('demo:northstar');p=await store.analyze(p.account.id,p.account.version);const version=p.account.version;p=await store.execute(p.account.id,version);await assert.rejects(store.execute(p.account.id,version),/changed/);await assert.rejects(store.execute(p.account.id,p.account.version));assert.equal((await store.profile(p.account.id)).actions.length,1);});
test('concurrent approval reserves only one intervention',async()=>{const {store}=fixture();await store.seed();let p=await store.profile('demo:northstar');p=await store.analyze(p.account.id,p.account.version);const results=await Promise.allSettled([store.execute(p.account.id,p.account.version),store.execute(p.account.id,p.account.version)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal((await store.profile(p.account.id)).actions.length,1);});
test('new activity invalidates the draft and ingestion updates risk',async()=>{const {store}=fixture();await store.seed();let p=await store.profile('demo:northstar');p=await store.analyze(p.account.id,p.account.version);p=await store.appendEvents(p.account.id,p.account.version,[{id:'demo:northstar:resolved',kind:'integration_restored',at:clock.toISOString(),summary:'SIMULATED: connection restored.',data:{},synthetic:true}]);assert.equal(p.risk.score,45);await assert.rejects(store.execute(p.account.id,p.account.version),/evidence or policy changed/i);});
test('invalid AI output falls back with an explicit label and remains unapproved',async()=>{const {store}=fixture({ai:async()=>({action:'invented',engine:'gemini'})});await store.seed();let p=await store.profile('demo:northstar');p=await store.analyze(p.account.id,p.account.version);assert.equal(p.decision.diagnosis.engine,'deterministic');assert.match(p.decision.diagnosis.fallbackReason,/failed validation/);assert.equal(p.actions.length,0);});
test('provider unavailable uses explicit fallback, not a fake live AI response',async()=>{const {store}=fixture({ai:async()=>{throw Error('network')}});await store.seed();let p=await store.profile('demo:northstar');p=await store.analyze(p.account.id,p.account.version);assert.equal(p.decision.diagnosis.engine,'deterministic');});
test('test email records acceptance without claiming delivery',async()=>{let sent=0;const {store}=fixture({deliver:async()=>{sent++;return 'test-provider-id'}});await store.seed();await store.setPolicy('resolve-demo',{...defaultPolicy,mode:'test_email'});let p=await store.profile('demo:northstar');p=await store.analyze(p.account.id,p.account.version);p=await store.execute(p.account.id,p.account.version);assert.equal(sent,1);assert.equal(p.actions[0].status,'accepted');assert.equal(p.actions[0].providerId,'test-provider-id');assert(p.audit.some(a=>/Delivery has not been confirmed/.test(a.detail)));assert.equal(p.risk.score,90);});
test('provider timeout is unknown and cannot silently retry',async()=>{let sent=0;const {store}=fixture({deliver:async()=>{sent++;throw Error('timeout')}});await store.seed();await store.setPolicy('resolve-demo',{...defaultPolicy,mode:'test_email'});let p=await store.profile('demo:northstar');p=await store.analyze(p.account.id,p.account.version);p=await store.execute(p.account.id,p.account.version);assert.equal(p.actions[0].status,'unknown');await assert.rejects(store.execute(p.account.id,p.account.version));assert.equal(sent,1);});
test('unconfigured test email is rejected before reserving or sending',async()=>{const {store}=fixture();await store.seed();await store.setPolicy('resolve-demo',{...defaultPolicy,mode:'test_email'});let p=await store.profile('demo:northstar');p=await store.analyze(p.account.id,p.account.version);await assert.rejects(store.execute(p.account.id,p.account.version),/not configured/);assert.equal((await store.profile(p.account.id)).actions.length,0);});
test('explicit automation executes once, while opt-outs and recent outreach stay blocked',async()=>{const {store}=fixture();await store.seed();await store.setPolicy('resolve-demo',{...defaultPolicy,automatic:true});let p=await store.profile('demo:northstar');p=await store.analyze(p.account.id,p.account.version);assert.equal(p.actions.length,1);assert.equal(p.actions[0].approvedBy,'explicit-automatic-policy');for(const id of ['demo:harbor','demo:luma']){let p=await store.profile(id),count=p.actions.length;p=await store.analyze(id,p.account.version);assert.equal(p.actions.length,count);assert(['internal_review','no_action'].includes(p.decision.diagnosis.action));}});
test('cooldown expires after the configured interval',()=>{const action={id:'a',status:'accepted',createdAt:new Date(clock.getTime()-73*3600000).toISOString(),completedAt:null};assert.equal(outreachBlock(northstar.account,[action],clock,defaultPolicy),null);assert.match(outreachBlock(northstar.account,[{...action,createdAt:clock.toISOString()}],clock,defaultPolicy),/72-hour/);});
test('reset removes only synthetic demo history and returns risk to 90',async()=>{const {store,sqlite}=fixture();sqlite.prepare('INSERT INTO companies(id,shop_domain) VALUES(?,?)').run('test-shop','test-shop');sqlite.prepare('INSERT INTO customers(id,company_id,shopify_id,email,synced_at) VALUES(?,?,?,?,?)').run('test-shop:7','test-shop','7','test@example.com',clock.toISOString());await store.registerShopify('test-shop');await store.seed();let p=await store.profile('demo:northstar');p=await store.analyze(p.account.id,p.account.version);p=await store.execute(p.account.id,p.account.version);await store.reengage(p.account.id,p.account.version);await store.seed(true);p=await store.profile('demo:northstar');assert.equal(p.risk.score,90);assert.equal(p.actions.length,0);assert.equal(p.decision,null);assert.equal((await store.profile('shopify:test-shop:7')).account.email,'test@example.com');assert.equal(p.policy.automatic,false);});
test('real Shopify adapter scopes customer history to the store and marks missing signals unavailable',async()=>{const {store,sqlite}=fixture();sqlite.prepare('INSERT INTO companies(id,shop_domain) VALUES(?,?)').run('test-shop','test-shop');sqlite.prepare('INSERT INTO customers(id,company_id,shopify_id,email,synced_at) VALUES(?,?,?,?,?)').run('test-shop:7','test-shop','7','test@example.com',clock.toISOString());for(const [id,shop] of [['good','test-shop'],['other','other-shop']])sqlite.prepare('INSERT INTO recovery_records(id,customer_id,name,signal,context,status,decision,source,import_id,created_at,updated_at,version) VALUES(?,?,?,?,?,?,?,?,?,?,?,1)').run(id,'7','7','orders/cancelled',JSON.stringify({shop,cancel_reason:'customer'}),'pending','{}','shopify','stream-shopify',clock.toISOString(),clock.toISOString());await store.registerShopify('test-shop');const p=await store.profile('shopify:test-shop:7');assert.equal(p.events.length,1);assert.equal(p.events[0].id,'good');assert.equal(p.account.profile.plan,null);assert.equal(p.account.profile.onboarding,null);assert.equal(p.account.profile.emailConsent,'unknown');await assert.rejects(store.reengage(p.account.id,p.account.version));await assert.rejects(store.setPolicy('test-shop',defaultPolicy),/restricted/);});
