import {env} from '@resolve/runtime';
import {authorizedShop,agentTick,agentRuntime,connection,domainVerified} from '@/lib/agent-runtime';
import {database,safeMutation,storageError} from '@/lib/storage';
import {merchantPolicySchema,productionBlock} from '@/lib/merchant-policy';
export async function GET(req:Request){const shop=await authorizedShop(req);if(!shop)return Response.json({error:'Connect Shopify to continue.'},{status:401});try{const db=database(),r=agentRuntime(shop),settings=await r.commerce.settings(shop),[jobs,checkpoints,anonymous,outcomes,inbox]=await Promise.all([db.prepare('SELECT * FROM retention_jobs WHERE shop=? ORDER BY created_at DESC LIMIT 50').bind(shop).all(),db.prepare('SELECT * FROM sync_checkpoints WHERE shop=?').bind(shop).all(),db.prepare('SELECT kind,occurred_at,source,identity_basis FROM shopping_events WHERE shop=? AND customer_id IS NULL ORDER BY occurred_at DESC LIMIT 30').bind(shop).all(),db.prepare('SELECT * FROM retention_outcomes WHERE shop=? ORDER BY at DESC LIMIT 20').bind(shop).all(),db.prepare('SELECT topic,status,detail,created_at FROM webhook_inbox WHERE shop=? ORDER BY created_at DESC LIMIT 10').bind(shop).all()]);const conn=await db.prepare('SELECT shop FROM merchant_connections WHERE shop=? AND revoked_at IS NULL').bind(shop).first();return Response.json({shop,settings,jobs:jobs.results,checkpoints:checkpoints.results,anonymous:anonymous.results,outcomes:outcomes.results,inbox:inbox.results,aiConfigured:!!env.GEMINI_API_KEY,testEmailConfigured:!!env.RESEND_API_KEY&&!!env.EMAIL_TEST_TO,productionBlock:productionBlock(settings,{authenticated:!!conn,domainVerified:await domainVerified(settings.senderEmail),provider:!!env.RESEND_API_KEY,publicUrl:!!env.PUBLIC_APP_URL?.startsWith('https://')&&!env.PUBLIC_APP_URL.includes('trycloudflare.com')})},{headers:{'Cache-Control':'no-store'}});}catch(e){return storageError(e)}}
export async function POST(req:Request){if(!safeMutation(req))return new Response('Invalid origin',{status:403});const shop=await authorizedShop(req);if(!shop)return new Response('Unauthorized',{status:401});try{const b=await req.json() as {action?:string;settings?:unknown};const r=agentRuntime(shop);if(b.action==='settings'){
 const value=merchantPolicySchema.parse(b.settings);
 if(value.automatic&&value.mode==='customer_email'){
 const c=await connection(shop),blocked=productionBlock(value,{authenticated:c.authenticated,domainVerified:await domainVerified(value.senderEmail),provider:!!env.RESEND_API_KEY,publicUrl:!!env.PUBLIC_APP_URL?.startsWith('https://')&&!env.PUBLIC_APP_URL.includes('trycloudflare.com')});
 if(blocked)return Response.json({error:blocked},{status:409});
 }
 return Response.json({settings:await r.commerce.saveSettings(shop,value)});
 }if(b.action==='sync'){const c=await connection(shop);return Response.json({sync:await r.commerce.sync(shop,c.graphql),detection:await r.commerce.detect(shop)});}if(b.action==='run')return Response.json(await agentTick(shop));return new Response('Unknown action',{status:400});}catch(e){return storageError(e)}}
