export const judgeCases = [
 {id:'checkout',name:'Ava',title:'Checkout left incomplete',story:'Ava viewed Trail Shoes, added them to the cart, and started checkout. Five hours passed without a completed purchase.',expected:'checkout_recovery',expectedLabel:'Offer checkout help',reason:'An incomplete checkout supports a helpful follow-up when permission allows it. The reason for stopping is unknown.'},
 {id:'bluepeak',name:'Leo',title:'Browsing without a purchase',story:'Leo viewed a backpack and a collection. No cart, checkout, or purchase was recorded.',expected:'no_action',expectedLabel:'Observe without emailing',reason:'Viewing products is normal shopping behavior. It does not prove a problem or justify an email.'},
 {id:'meridian',name:'Maya',title:'Purchase already completed',story:'Maya paused checkout, then completed an order before any retention message was sent.',expected:'no_action',expectedLabel:'No recovery message needed',reason:'A completed purchase resolves the incomplete checkout. Do not send an outdated reminder.'},
 {id:'pine',name:'Oliver',title:'Customer-requested cancellation',story:'Oliver bought a water bottle and then requested cancellation. No specific explanation was provided.',expected:'post_cancellation_followup',expectedLabel:'Offer cancellation support',reason:'Offer help without assuming dissatisfaction, financial difficulty, or a reason that was not recorded.'},
 {id:'harbor',name:'Noah',title:'Email permission withdrawn',story:'Noah has an incomplete checkout, but has opted out of email.',expected:'internal_review',expectedLabel:'Internal review only',reason:'An opportunity to help does not override the customer’s communication preference.'},
 {id:'luma',name:'Emma',title:'A message was already sent',story:'Emma has an incomplete checkout. A previous demo message was simulated one hour ago.',expected:'no_action',expectedLabel:'Wait; do not send again',reason:'The 72-hour contact limit prevents repeated messages. The earlier message is seeded synthetic history.'},
 {id:'northstar',name:'Northstar',title:'Integration trouble (SaaS example)',story:'A fictional SaaS customer had three CRM connection failures, an open support request, and falling usage.',expected:'troubleshoot',expectedLabel:'Help restore the integration',reason:'Help with the observed technical problem. This is a synthetic SaaS example, not a connected Shopify or CRM account.'},
] as const;
export function judgeCase(accountId:string){return judgeCases.find(item=>accountId.endsWith(`:${item.id}`));}
export const judgeInstructions = `Resolve judge demo\nNo account or password required. All customers and outcomes are fictional.\n1. Click Start judge demo to open Ava’s shopping journey.\n2. Read the timeline: product viewed → added to cart → checkout started → incomplete checkout.\n3. Click Analyze with AI. Read the possible cause, uncertainty, cited evidence, and draft. The engine label tells you whether Gemini or fallback rules were used.\n4. Click Approve & simulate delivery. No real email is sent.\n5. Click Simulate re-engagement to add a fictional completed checkout and inspect the revised score.\n6. Reload to inspect persisted history. Open All customers to compare Leo, Maya, Oliver, Noah, Emma, and Northstar.\nBrowsing alone, completed purchases, opt-outs, and recent outreach should not produce another email.\nExpand Explore the fictional data to inspect every example and download the complete JSON dataset without a database or AI call.
If Storage is unavailable appears, the hosted database needs repair; a password will not fix it.`;
