export type RecoveryDecision={tool:string;title:string;reason:string;message:string;execution:string;engine?:string;model?:string};
export type RecoveryRecord={id:string;customer_id:string;name:string;signal:string;context:Record<string,string>;status:string;decision:RecoveryDecision;source:string;import_id:string;ticket:string|null;created_at:string;updated_at:string;version:number};
export const STATUS:Record<string,string>={pending:'Needs review',active:'Awaiting response',escalated:'Escalated',resolved:'Resolved'};
export function recommend(signal:string,context:Record<string,string>):RecoveryDecision {
 const value=signal.toLowerCase();
 if(['unsupported_format','upload_failed','format'].includes(value)&&(!context.error_code||context.error_code==='unsupported_format'))return {tool:'show_guide',title:'Step-by-step guidance',reason:'The source recorded an unsupported file format event.',message:'Check the uploaded file format. CSV imports require a header row, unique customer IDs, and consistent column counts.',execution:'Guidance was prepared as a customer response in the dashboard.'};
 if(['server_error','technical_error','500'].includes(value)||context.error_code==='500')return {tool:'create_support_ticket',title:'Technical support',reason:'The source reports a technical error. The agent cannot repair the underlying system itself.',message:'The technical issue was recorded and an internal support request was created.',execution:'An internal support request was created with the relevant context.'};
 if(['price_objection','price'].includes(value))return {tool:'ask_user',title:'Clarify the budget',reason:'An explicit pricing concern was recorded. No verified plan catalogue is connected.',message:'Which features do you need, and what monthly budget works for you? We can use that to clarify the available options.',execution:'A question was prepared to clarify pricing needs without inventing discounts or plans.'};
 const profile=Object.entries(context).filter(([k])=>['tenure','Contract','MonthlyCharges'].includes(k)).map(([k,v])=>`${k}: ${v}`).join(' · ');
 return {tool:'ask_user',title:'Clarify the cause',reason:profile?`${profile}. These account details do not establish a specific cause.`:'This signal alone does not identify the specific problem.',message:'What is making it difficult to use the product? Could you describe the issue in one sentence?',execution:'A clarifying question was prepared in the dashboard.'};
}
export function unpack(row:Record<string,unknown>):RecoveryRecord{return {...row,context:JSON.parse(row.context as string),decision:JSON.parse(row.decision as string)} as RecoveryRecord}
