import {retentionStore} from './retention-store.ts';
import {eventSchema,type RetentionEvent} from './retention-core.ts';
import {defaultMerchantPolicy,merchantPolicySchema,marketingConsent,cancellationEligible,type MerchantPolicy} from './merchant-policy.ts';
import {STREAM_QUERY,CUSTOMER_FIELDS,CUSTOMER_MINIMAL_FIELDS,type shopifyClient} from './shopify-client.ts';
type Graphql=ReturnType<typeof shopifyClient>;
export type CustomerNode={id:string;firstName?:string|null;lastName?:string|null;createdAt:string;updatedAt:string;tags?:string[];numberOfOrders?:string;amountSpent?:{amount:string;currencyCode:string};defaultEmailAddress?:{emailAddress:string;marketingState:string;marketingUpdatedAt?:string|null;marketingUnsubscribeUrl?:string}|null};
export type OrderNode={id:string;name:string;createdAt:string;updatedAt:string;processedAt?:string|null;cancelledAt?:string|null;cancelReason?:string|null;displayFinancialStatus?:string;displayFulfillmentStatus?:string;customer?:{id:string}|null;totalPriceSet?:{shopMoney:{amount:string;currencyCode:string}};lineItems?:{nodes:{title:string;quantity:number}[]};refunds?:{id:string;createdAt:string}[]};
export type CheckoutNode={id:string;createdAt:string;updatedAt:string;completedAt?:string|null;abandonedCheckoutUrl?:string;customer?:{id:string}|null;lineItems?:{nodes:{title:string;quantity:number}[]};totalPriceSet?:{shopMoney:{amount:string;currencyCode:string}};nativeEmailState?:'not_sent'|'unknown'};
const numericId=(id:string)=>{const part=id.split('/').pop()!;if(!/^\d+$/.test(part))throw Error('Invalid Shopify resource ID.');return part;};
export const accountId=(shop:string,id:string)=>`shopify:${shop}:${numericId(id)}`;
export function commerceStore(db:D1Database,clock=()=>new Date()){
 const at=()=>clock().toISOString();
 async function settings(shop:string):Promise<MerchantPolicy>{const row=await db.prepare('SELECT body FROM merchant_settings WHERE shop=?').bind(shop).first();return row?merchantPolicySchema.parse(JSON.parse(String(row.body))):{...defaultMerchantPolicy};}
 async function saveSettings(shop:string,input:unknown){const value=merchantPolicySchema.parse(input);await db.batch([db.prepare('INSERT INTO merchant_settings(shop,body,updated_at) VALUES(?,?,?) ON CONFLICT(shop) DO UPDATE SET body=excluded.body,version=version+1,updated_at=excluded.updated_at').bind(shop,JSON.stringify(value),at()),db.prepare('INSERT INTO retention_settings(workspace,body) VALUES(?,?) ON CONFLICT(workspace) DO UPDATE SET body=excluded.body').bind(shop,JSON.stringify({automatic:false,mode:value.mode,cooldownHours:value.cooldownHours,merchant:value}))]);return value;}
 async function snapshot(shop:string,kind:string,resourceId:string){const row=await db.prepare('SELECT body FROM commerce_snapshots WHERE shop=? AND kind=? AND resource_id=?').bind(shop,kind,resourceId).first();return row?JSON.parse(String(row.body)):null;}
 async function saveSnapshot(shop:string,kind:string,node:{id:string;updatedAt?:string;customer?:{id:string}|null}){
 await db.prepare('INSERT INTO commerce_snapshots(shop,kind,resource_id,customer_id,body,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(shop,kind,resource_id) DO UPDATE SET customer_id=excluded.customer_id,body=excluded.body,updated_at=excluded.updated_at WHERE excluded.updated_at>=commerce_snapshots.updated_at').bind(shop,kind,node.id,kind==='customer'?numericId(node.id):node.customer?numericId(node.customer.id):null,JSON.stringify(node),node.updatedAt||at()).run();
 }
 async function customer(shop:string,node:CustomerNode){
 numericId(node.id);const previous=await snapshot(shop,'customer',node.id);if(previous&&previous.updatedAt>node.updatedAt)return;
 await db.prepare('INSERT INTO companies(id,shop_domain) VALUES(?,?) ON CONFLICT(id) DO NOTHING').bind(shop,shop).run();
 const email=node.defaultEmailAddress?.emailAddress||null,id=numericId(node.id),name=[node.firstName,node.lastName].filter(Boolean).join(' ')||`Customer ${id.slice(-6)}`;
 const profile={plan:null,mrr:null,onboarding:null,purchase:`${node.numberOfOrders??'Unknown'} lifetime orders${node.amountSpent?` · ${node.amountSpent.currencyCode} ${node.amountSpent.amount} spent`:''}. Purchase timeline covers authorized synchronized history.`,emailConsent:marketingConsent(node.defaultEmailAddress?.marketingState),commerce:{createdAt:node.createdAt,orders:node.numberOfOrders??null,spending:node.amountSpent??null,tags:node.tags||[],consentState:node.defaultEmailAddress?.marketingState||'UNKNOWN',consentUpdatedAt:node.defaultEmailAddress?.marketingUpdatedAt||null,unsubscribeUrl:node.defaultEmailAddress?.marketingUnsubscribeUrl||null}};
 await db.batch([db.prepare('INSERT INTO customers(id,company_id,shopify_id,email,synced_at) VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET email=excluded.email,synced_at=excluded.synced_at').bind(`${shop}:${id}`,shop,id,email,at()),db.prepare('INSERT INTO retention_accounts(id,workspace,name,email,source,profile,version) VALUES(?,?,?,?,?,?,1) ON CONFLICT(id) DO UPDATE SET name=excluded.name,email=excluded.email,profile=excluded.profile,version=version+CASE WHEN retention_accounts.profile<>excluded.profile OR retention_accounts.email IS NOT excluded.email OR retention_accounts.name<>excluded.name THEN 1 ELSE 0 END').bind(accountId(shop,id),shop,name,email,'shopify',JSON.stringify(profile))]);await saveSnapshot(shop,'customer',node);
 }
 async function ensureAccount(shop:string,id:string){const key=accountId(shop,id);const row=await db.prepare('SELECT id FROM retention_accounts WHERE id=? AND workspace=?').bind(key,shop).first();if(!row){await db.prepare('INSERT INTO retention_accounts(id,workspace,name,email,source,profile,version) VALUES(?,?,?,?,?,?,1)').bind(key,shop,`Customer ${numericId(id).slice(-6)}`,null,'shopify',JSON.stringify({plan:null,mrr:null,purchase:null,onboarding:null,emailConsent:'unknown'})).run()}return key;}
 async function event(shop:string,customerId:string,event:RetentionEvent,source='admin_api',identity='shopify_customer'){
 const key=await ensureAccount(shop,customerId);const body=eventSchema.parse(event);
 const result=await db.batch([db.prepare('INSERT OR IGNORE INTO retention_events(id,account_id,body) VALUES(?,?,?)').bind(event.id,key,JSON.stringify(body)),db.prepare('UPDATE retention_accounts SET version=version+1 WHERE id=? AND changes()=1').bind(key),db.prepare('INSERT OR IGNORE INTO shopping_events(shop,event_id,customer_id,kind,occurred_at,source,identity_basis,body) VALUES(?,?,?,?,?,?,?,?)').bind(shop,event.id,numericId(customerId),event.kind,event.at,source,identity,JSON.stringify(body))]);return result[0].meta.changes===1;
 }
 async function enqueue(shop:string,customerId:string,e:RetentionEvent){const key=await ensureAccount(shop,customerId);await event(shop,customerId,e,'deterministic_detection');await db.prepare('INSERT OR IGNORE INTO retention_jobs(id,shop,account_id,trigger_id,trigger_kind,status,due_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),shop,key,e.id,e.kind,'pending',at(),at(),at()).run();}
 async function order(shop:string,node:OrderNode){
 await saveSnapshot(shop,'order',node);if(!node.customer)return;
 const id=numericId(node.id),customerId=node.customer.id,base={orderId:node.id,orderName:node.name,products:(node.lineItems?.nodes.map(v=>`${v.title} × ${v.quantity}`).join(', ')||'Products unavailable').slice(0,500),source:'Shopify Admin API'};
 await event(shop,customerId,{id:`${shop}:order:${id}:created`,kind:'order_created',at:node.createdAt,summary:`Order ${node.name} was created. ${base.products}`.slice(0,600),data:base,synthetic:false});
 if(['PAID','PARTIALLY_REFUNDED','REFUNDED'].includes(node.displayFinancialStatus||'')){
 const when=node.processedAt||node.createdAt;await event(shop,customerId,{id:`${shop}:order:${id}:paid`,kind:'order_paid',at:when,summary:`Purchase ${node.name} was recorded as paid. ${base.products}`.slice(0,600),data:base,synthetic:false});
 const actions=await db.prepare('SELECT id,body FROM retention_actions WHERE account_id=?').bind(accountId(shop,customerId)).all();for(const row of actions.results){const a=JSON.parse(String(row.body));if(['accepted','delivered'].includes(a.status)&&a.createdAt<when&&new Date(when).getTime()-new Date(a.createdAt).getTime()<30*86400000){await db.prepare('INSERT OR IGNORE INTO retention_outcomes(shop,action_id,order_id,at,detail) VALUES(?,?,?,?,?)').bind(shop,row.id,node.id,when,'Purchase observed within 30 days after outreach. Association only; causation is not established.').run();}}
 }
 if(node.cancelledAt){const e:RetentionEvent={id:`${shop}:order:${id}:cancelled`,kind:'order_cancelled',at:node.cancelledAt,summary:`Order ${node.name} was cancelled. Shopify reason: ${node.cancelReason||'not provided'}.`,data:{...base,reason:(node.cancelReason||'unknown').toLowerCase()},synthetic:false};await event(shop,customerId,e);if(cancellationEligible(node.cancelReason||undefined))await enqueue(shop,customerId,e);}
 if(node.displayFulfillmentStatus==='FULFILLED')await event(shop,customerId,{id:`${shop}:order:${id}:fulfilled`,kind:'order_fulfilled',at:node.updatedAt,summary:`Order ${node.name} is fulfilled.`,data:base,synthetic:false});
 for(const refund of node.refunds||[])await event(shop,customerId,{id:`${shop}:refund:${numericId(refund.id)}`,kind:'refund_issued',at:refund.createdAt,summary:`A refund was recorded for ${node.name}.`,data:base,synthetic:false});
 }
 async function checkout(shop:string,node:CheckoutNode){await saveSnapshot(shop,'checkout',node);if(node.completedAt&&node.customer)await event(shop,node.customer.id,{id:`${shop}:checkout:${numericId(node.id)}:recovered`,kind:'checkout_recovered',at:node.completedAt,summary:'Shopify confirmed checkout completion.',data:{checkoutId:node.id},synthetic:false});}
 async function sync(shop:string,graphql:Graphql,pagesPerStream=2){
 const result:Record<string,{count:number;complete:boolean;error?:string}>={};
 for(const kind of ['customers','orders','checkouts'] as const){let count=0,complete=false;const cp=await db.prepare('SELECT * FROM sync_checkpoints WHERE shop=? AND kind=?').bind(shop,kind).first();let cursor=cp?.cursor?String(cp.cursor):null;const cycle=cp?.cycle_started?String(cp.cycle_started):at();const since=cp?.since?new Date(new Date(String(cp.since)).getTime()-300000).toISOString():new Date(clock().getTime()-59*86400000).toISOString();
 try{for(let page=0;page<pagesPerStream;page++){
 let data:Record<string,{nodes:unknown[];pageInfo:{hasNextPage:boolean;endCursor:string}}>;
 try{data=await graphql(STREAM_QUERY[kind],{after:cursor,query:`updated_at:>=${since}`});}catch(e){if(kind!=='customers'||!String(e).includes('not approved'))throw e;data=await graphql(STREAM_QUERY.customers.replace(CUSTOMER_FIELDS,CUSTOMER_MINIMAL_FIELDS),{after:cursor,query:`updated_at:>=${since}`});}const connection=data[kind==='checkouts'?'abandonedCheckouts':kind];
 for(const raw of connection.nodes){if(kind==='customers')await customer(shop,raw as CustomerNode);else if(kind==='orders')await order(shop,raw as OrderNode);else await checkout(shop,{...raw as CheckoutNode,nativeEmailState:'unknown'});count++;}
 cursor=connection.pageInfo.hasNextPage?connection.pageInfo.endCursor:null;complete=!connection.pageInfo.hasNextPage;
 await db.prepare('INSERT INTO sync_checkpoints(shop,kind,cursor,since,cycle_started,last_success,error) VALUES(?,?,?,?,?,?,NULL) ON CONFLICT(shop,kind) DO UPDATE SET cursor=excluded.cursor,since=excluded.since,cycle_started=excluded.cycle_started,last_success=excluded.last_success,error=NULL').bind(shop,kind,cursor,complete?cycle:cp?.since||null,complete?null:cycle,at()).run();if(complete)break;
 }}catch(error){const detail=error instanceof Error?error.message:'Synchronization failed';await db.prepare('INSERT INTO sync_checkpoints(shop,kind,error) VALUES(?,?,?) ON CONFLICT(shop,kind) DO UPDATE SET error=excluded.error').bind(shop,kind,detail).run();result[kind]={count,complete,error:detail};continue;}result[kind]={count,complete};}
 await db.prepare('UPDATE companies SET synced_at=? WHERE id=?').bind(at(),shop).run();return result;
 }
 async function detect(shop:string){
 const p=await settings(shop),rows=await db.prepare("SELECT body FROM commerce_snapshots WHERE shop=? AND kind='checkout'").bind(shop).all();let detected=0;
 for(const row of rows.results){const c=JSON.parse(String(row.body)) as CheckoutNode;if(!c.customer||c.completedAt||clock().getTime()-new Date(c.updatedAt).getTime()<p.checkoutWaitHours*3600000)continue;
 const e:RetentionEvent={id:`${shop}:checkout:${numericId(c.id)}:abandoned`,kind:'checkout_abandoned',at:new Date(new Date(c.updatedAt).getTime()+p.checkoutWaitHours*3600000).toISOString(),summary:`Checkout remained incomplete after ${p.checkoutWaitHours} hours without updates. Cause is unknown.`,data:{checkoutId:c.id,lastActivityAt:c.updatedAt,products:(c.lineItems?.nodes.map(i=>`${i.title} × ${i.quantity}`).join(', ')||'Unavailable').slice(0,500),source:'Shopify abandonedCheckouts query',confidence:'medium'},synthetic:false};await enqueue(shop,c.customer.id,e);detected++;
 }
 const accounts=await db.prepare("SELECT id FROM retention_accounts WHERE workspace=? AND source='shopify'").bind(shop).all();for(const account of accounts.results){const profile=await retentionStore({db,now:clock}).profile(String(account.id));const paid=profile.events.filter(e=>e.kind==='order_paid').sort((a,b)=>a.at.localeCompare(b.at));if(paid.length>=3){const intervals=paid.slice(1).map((e,i)=>(new Date(e.at).getTime()-new Date(paid[i].at).getTime())/86400000).filter(d=>d>=1).sort((a,b)=>a-b);if(intervals.length>=2){const usual=intervals[Math.floor(intervals.length/2)],last=paid.at(-1)!,days=(clock().getTime()-new Date(last.at).getTime())/86400000;if(days>=Math.max(p.minimumInactiveDays,usual*p.inactivityMultiplier)){await enqueue(shop,profile.account.id.split(':').at(-1)!,{id:`${shop}:inactive:${profile.account.id.split(':').at(-1)}:${last.data.orderId}`,kind:'customer_inactive',at:at(),summary:`No synchronized purchase for ${Math.floor(days)} days; observed median interval was ${Math.round(usual)} days across ${paid.length} purchases. Limited to authorized history.`,data:{days:Math.floor(days),usualDays:Math.round(usual),orderId:String(last.data.orderId),confidence:'medium'},synthetic:false});detected++;}}}
 const active=profile.events.filter(e=>e.kind==='product_added_to_cart'||e.kind==='product_viewed');const last=active.at(-1);if(last&&last.data.identityBasis==='signed_app_proxy'&&last.data.marketingAllowed===true){const subsequent=profile.events.some(e=>e.at>last.at&&['order_created','order_paid','checkout_started','product_removed_from_cart'].includes(e.kind));if(!subsequent&&last.kind==='product_added_to_cart'&&clock().getTime()-new Date(last.at).getTime()>=p.cartWaitHours*3600000){await enqueue(shop,profile.account.id.split(':').at(-1)!,{id:`${shop}:cart:${last.id}`,kind:'cart_abandoned',at:at(),summary:`Identified cart activity had no subsequent checkout or order after ${p.cartWaitHours} hours. Browser tracking may be incomplete.`,data:{basisId:last.id,confidence:'medium',product:String(last.data.product||'Unavailable')},synthetic:false});detected++;}else if(!subsequent&&active.filter(e=>e.kind==='product_viewed').length>=3){await event(shop,profile.account.id.split(':').at(-1)!,{id:`${shop}:browse:${last.id}`,kind:'browsing_interest',at:at(),summary:'Repeated product interest without a synchronized purchase. Weak signal; no automated email.',data:{confidence:'low'},synthetic:false},'deterministic_detection');}}
 }return {detected};
 }
 return {settings,saveSettings,snapshot,saveSnapshot,customer,order,checkout,event,enqueue,sync,detect};
}
