'use client';
import {useEffect,useState} from 'react';
import {Activity,RefreshCw,Save,ShieldCheck,Mail,ArrowUpRight} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import type {MerchantPolicy} from '@/lib/merchant-policy';
import './retention.css';
type Data={shop:string;settings:MerchantPolicy;aiConfigured:boolean;testEmailConfigured:boolean;productionBlock:string|null;jobs:{id:string;trigger_kind:string;status:string;detail:string|null;created_at:string}[];checkpoints:{kind:string;last_success:string|null;error:string|null}[];anonymous:{kind:string;occurred_at:string;identity_basis:string}[];outcomes:{action_id:string;order_id:string;at:string;detail:string}[];inbox:{topic:string;status:string;detail:string|null;created_at:string}[]};
export default function AgentOperations(){
 const [data,setData]=useState<Data|null>(null),[policy,setPolicy]=useState<MerchantPolicy|null>(null),[busy,setBusy]=useState(''),[notice,setNotice]=useState(''),[error,setError]=useState('');
 async function load(){const r=await fetch('/api/agent',{cache:'no-store'}),b=await r.json() as Data&{error?:string};if(!r.ok)throw Error(b.error||'Agent diagnostics unavailable.');setData(b);setPolicy(b.settings)}
 useEffect(()=>{void load().catch(e=>setError(e.message));},[]);
 async function action(action:string){setBusy(action);setError('');setNotice('');try{const r=await fetch('/api/agent',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...(action==='settings'?{settings:policy}:{})})}),b=await r.json() as Data&{error?:string};if(!r.ok)throw Error(b.error||'Operation failed.');await load();setNotice(action==='settings'?'Merchant settings saved. Existing drafts must be analyzed again.':'Cycle completed. Check each data source and job status below.');}catch(e){setError((e as Error).message)}finally{setBusy('')}}
 function update<K extends keyof MerchantPolicy>(key:K,value:MerchantPolicy[K]){setPolicy(p=>p?{...p,[key]:value}:p)}
 return <div className="rt-workspace agent-ops"><div className="rt-top"><div><h1>Agent operations</h1><p>A continuous shopping history. Thoughtful outreach. Clear evidence.</p></div><Button disabled={!!busy} onClick={()=>action('run')}><Activity size={16}/>{busy==='run'?'Running cycle…':'Run a cycle'}</Button></div>
 {error?<p role="alert" className="rt-warning">{error}</p>:null}{notice?<p role="status" className="agent-notice">{notice}</p>:null}
 {!data||!policy?<p className="rt-muted">Loading merchant controls…</p>:<>
 <div className="rt-overview"><div><span>Connected store</span><strong className="agent-shop">{data.shop.replace('.myshopify.com','')}</strong><small>Real Shopify data · separate from the demo</small></div><div><span>Outreach policy</span><strong>{policy.automatic?'Automatic':'Manual'}</strong><small>{policy.mode==='test_email'?'Only your configured test address':policy.mode==='simulation'?'Simulation · no email':'Customer email · prerequisites enforced'}</small></div><div><span>Intelligence</span><strong>{data.aiConfigured?'Gemini':'Rules'}</strong><small>Automatic outreach requires validated live analysis</small></div></div>
 <div className="rt-demo-callout"><span className="rt-demo-icon"><ShieldCheck/></span><div><h2>Production readiness</h2><p>{data.productionBlock||'Authenticated merchant access and email sender verification passed. Consent, suppression, timing and fresh purchase checks still apply per message.'}</p><small>A local test runner works while this computer and server are running. Cloud deployments use a five-minute scheduled worker.</small></div></div>
 <div className="agent-grid"><section className="rt-panel"><div className="rt-section-head"><h2>Merchant voice & delivery</h2><Mail size={18}/></div><div className="agent-fields">{([['brandName','Brand name'],['senderName','Sender name'],['senderEmail','Verified sender email'],['replyTo','Reply-to email'],['postalAddress','Merchant postal address']] as const).map(([key,label])=><label key={key}>{label}<Input value={policy[key]} onChange={e=>update(key,e.target.value)}/></label>)}<label>Brand voice<textarea value={policy.brandVoice} onChange={e=>update('brandVoice',e.target.value)} maxLength={600}/></label><label>Language<Input value="English" readOnly/></label><label>Delivery mode<select value={policy.mode} onChange={e=>update('mode',e.target.value as MerchantPolicy['mode'])}><option value="simulation">Simulate delivery</option><option value="test_email" disabled={!data.testEmailConfigured}>Restricted test email</option><option value="customer_email">Real customer email</option></select></label></div></section>
 <section className="rt-panel"><div className="rt-section-head"><h2>Timing & permission</h2><ShieldCheck size={18}/></div><div className="agent-fields">{([['cooldownHours','Hours between outreach',24,720],['checkoutWaitHours','Checkout waiting period (hours)',1,168],['cartWaitHours','Cart waiting period (hours)',4,168],['minimumInactiveDays','Minimum inactivity (days)',30,365],['inactivityMultiplier','Purchase interval multiplier',2,5]] as const).map(([key,label,min,max])=><label key={key}>{label}<Input type="number" min={min} max={max} value={policy[key]} onChange={e=>update(key,Number(e.target.value))}/></label>)}<fieldset><legend>Allowed strategies</legend>{(['checkout_recovery','cart_recovery','post_cancellation_followup','reengagement'] as const).map(key=><label className="agent-check" key={key}><input type="checkbox" checked={policy.allowed.includes(key)} onChange={e=>update('allowed',e.target.checked?[...policy.allowed,key]:policy.allowed.filter(v=>v!==key))}/>{key.replaceAll('_',' ')}</label>)}</fieldset><label className="agent-check"><input type="checkbox" checked={policy.otherRecoveryAutomation} onChange={e=>update('otherRecoveryAutomation',e.target.checked)}/>Another cart recovery flow is configured</label><label className="agent-check"><input type="checkbox" checked={policy.legalEligible} onChange={e=>update('legalEligible',e.target.checked)}/>I confirm merchant messaging eligibility</label><label className="agent-check"><input type="checkbox" checked={policy.automatic} disabled={policy.mode==='customer_email'&&!!data.productionBlock} onChange={e=>update('automatic',e.target.checked)}/>Automatically execute eligible Gemini recommendations</label><p className="rt-muted">Browsing alone never triggers an email. Unknown consent, recovery, duplicate attempts and recent contact suppress outreach.</p></div></section></div>
 <div className="rt-top-actions"><Button disabled={!!busy} onClick={()=>action('settings')}><Save size={16}/>Save settings</Button><Button variant="outline" disabled={!!busy} onClick={()=>action('sync')}><RefreshCw size={16}/>Sync Shopify</Button><a className="agent-link" href={`/auth/shopify/start?shop=${encodeURIComponent(data.shop)}`}>Authenticate merchant <ArrowUpRight size={14}/></a></div>
 <section className="rt-panel"><div className="rt-section-head"><h2>Source health</h2></div>{data.checkpoints.length?data.checkpoints.map(c=><article className="rt-action" key={c.kind}><strong>{c.kind}</strong><p>{c.error||`Last successful page: ${c.last_success||'Not synchronized yet'}`}</p></article>):<p className="rt-muted">Synchronize Shopify to initialize source checkpoints.</p>}<p className="rt-muted">Customer names may be unavailable without additional protected-data approval. Order history covers the authorized API window.</p></section>
 <section className="rt-panel"><div className="rt-section-head"><h2>Retention jobs</h2><span>{data.jobs.length} recent</span></div>{data.jobs.length?data.jobs.map(j=><article className="rt-action" key={j.id}><div><strong>{j.trigger_kind.replaceAll('_',' ')}</strong><span className="rt-outcome">{j.status.replaceAll('_',' ')}</span></div><p>{j.detail||'Waiting for background processing.'}</p><small>{new Date(j.created_at).toLocaleString('en-US')}</small></article>):<p className="rt-muted">No trigger jobs yet. Meaningful Shopify events will appear here.</p>}</section>
 <div className="agent-grid"><section className="rt-panel"><h2>Anonymous shopping activity</h2><p className="rt-muted">Client IDs are never treated as customer IDs. The Shopify Web Pixel must be deployed and activated before storefront events appear.</p>{data.anonymous.map((e,i)=><article className="rt-action" key={`${e.occurred_at}-${i}`}><strong>{e.kind.replaceAll('_',' ')}</strong><small>{new Date(e.occurred_at).toLocaleString('en-US')} · anonymous</small></article>)}{!data.anonymous.length?<p>No captured anonymous events yet.</p>:null}</section><section className="rt-panel"><h2>Observed outcomes</h2><p className="rt-muted">A later purchase is an association, not proof that the email caused it.</p>{data.outcomes.map(o=><article className="rt-action" key={`${o.action_id}-${o.order_id}`}><strong>{o.order_id}</strong><p>{o.detail}</p><small>{new Date(o.at).toLocaleString('en-US')}</small></article>)}{!data.outcomes.length?<p>No subsequent purchases recorded.</p>:null}</section></div>
 <section className="rt-panel"><h2>Verified webhook inbox</h2>{data.inbox.map((r,i)=><article className="rt-action" key={i}><strong>{r.topic} · {r.status}</strong>{r.detail?<p>{r.detail}</p>:null}<small>{new Date(r.created_at).toLocaleString('en-US')}</small></article>)}{!data.inbox.length?<p className="rt-muted">No new webhook receipts. API reconciliation runs independently.</p>:null}</section>
 </>}
 </div>;
}
