"use client";
import { useState } from 'react';
import { Upload, FileSpreadsheet, CheckCircle2 } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { parseCsv, normalizeCsv, type CsvData } from '@/lib/csv';
type Props={open:boolean;onOpenChange:(value:boolean)=>void;onImported:()=>void};
export default function ImportDialog({open,onOpenChange,onImported}:Props){
 const [csv,setCsv]=useState('');const [filename,setFilename]=useState('');const [data,setData]=useState<CsvData|null>(null);const [id,setId]=useState('');const [name,setName]=useState('none');const [signal,setSignal]=useState('none');const [source,setSource]=useState<'csv'|'ibm_sample'>('csv');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [success,setSuccess]=useState('');
 function prepare(text:string,file:string,origin:'csv'|'ibm_sample'){setError('');setSuccess('');try{const parsed=parseCsv(text);setCsv(text);setFilename(file);setData(parsed);setSource(origin);setId(parsed.headers.find(h=>['customer_id','customerid','id'].includes(h.toLowerCase()))||parsed.headers[0]);setName(parsed.headers.find(h=>['name','customer_name'].includes(h.toLowerCase()))||'none');setSignal(parsed.headers.find(h=>['signal','event','event_type'].includes(h.toLowerCase()))||'none')}catch(e){setError(e instanceof Error?e.message:'Could not read the file');setData(null)}}
 async function sample(){setBusy(true);setError('');try{const r=await fetch('/ibm-telco-sample.csv');if(!r.ok)throw Error('Could not load the sample.');prepare(await r.text(),'IBM Telco — 200 rows','ibm_sample')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function save(){if(!data)return;setBusy(true);setError('');try{const mapping={id,name:name==='none'?undefined:name,signal:signal==='none'?undefined:signal};normalizeCsv(data,mapping);const r=await fetch('/api/imports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({csv,filename,mapping,source})});const d=await r.json() as {error?:string;count:number;duplicate:boolean};if(!r.ok)throw Error(d.error);setSuccess(d.duplicate?`This file has already been imported. ${d.count} records exist.`:`Successfully imported ${d.count} customers.`);onImported()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <Dialog open={open} onOpenChange={v=>{if(!busy)onOpenChange(v)}}><DialogContent className="import-modal"><DialogHeader><span className="modal-icon"><FileSpreadsheet size={24}/></span><DialogTitle className="text-xl">Import CSV</DialogTitle><DialogDescription>Add customers, map columns, and review decisions.</DialogDescription></DialogHeader>
 {success?<div className="import-success"><CheckCircle2 size={36}/><h3>{success}</h3><Button onClick={()=>onOpenChange(false)}>View customers</Button></div>:<><label className="dropzone"><Upload size={28}/><strong>{filename||'Choose a CSV file'}</strong><span>UTF-8 · comma or semicolon · maximum 2 MB</span><input type="file" accept=".csv,text/csv" aria-label="Choose a CSV file" disabled={busy} onChange={async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>2000000){setError('The file exceeds 2 MB.');return}prepare(await f.text(),f.name,'csv')}}/></label><div className="sample-action"><span>Need a sample file?</span><Button variant="outline" disabled={busy} onClick={sample}>Load IBM sample</Button></div>
 {data&&<><div className="import-info"><strong>{data.rows.length} rows</strong><span>{data.headers.length} columns</span><span>{source==='ibm_sample'?'Public sample dataset':'Uploaded CSV'}</span></div><div className="mapping-grid">{[[id,setId,'Customer ID'],[name,setName,'Name (optional)'],[signal,setSignal,'Signal (optional)']].map(([value,setter,label],i)=><label key={i}><span>{label as string}</span><Select value={value as string} onValueChange={setter as (v:string)=>void}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{i>0&&<SelectItem value="none">None</SelectItem>}{data.headers.map(h=><SelectItem value={h} key={h}>{h}</SelectItem>)}</SelectContent></Select></label>)}</div><div className="csv-preview"><span>First 3 customer IDs</span><code>{data.rows.slice(0,3).map(r=>r[id]).join('  ·  ')}</code></div><p className="notice">{source==='ibm_sample'?'First 200 rows of the IBM Telco sample. These are not live customers. Churn labels and demographic columns are not passed to the agent.':'Without a signal, the agent chooses a clarifying question rather than inventing a cause.'}</p></>}
 {error&&<p role="alert" className="error-box">{error}</p>}<div className="modal-bottom"><a href="/recovery-template.csv" download>Download CSV template</a><Button disabled={!data||busy} onClick={save}>{busy?'Processing…':'Complete import'}</Button></div></>}
 </DialogContent></Dialog>
}
