"use client";
import { useState } from 'react';
import { X, Play, FileText, ShieldCheck, MessageSquare, CheckCircle2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import type { RecoveryRecord } from '@/lib/recovery';
import { recordTitle, signalLabel, contextLabel, contextValue } from '@/lib/presentation';
export default function Inspector({record,onClose,onUpdated}:{record:RecoveryRecord;onClose:()=>void;onUpdated:(r:RecoveryRecord)=>void}){
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [reply,setReply]=useState('');
 async function act(action:string){setBusy(true);setError('');try{const r=await fetch('/api/records',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:record.id,version:record.version,action,reply})});const d=await r.json() as RecoveryRecord & {error?:string};if(!r.ok)throw Error(d.error);onUpdated(d);setReply('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <aside className="inspector" aria-label="Decision details"><div className="inspector-heading"><h2>Decision details</h2><Button variant="ghost" size="icon" aria-label="Close details" onClick={onClose}><X size={19}/></Button></div><div className="identity"><span className="customer-avatar">{record.source==='shopify'?'S':record.name.slice(0,2).toUpperCase()}</span><div><h3>{recordTitle(record)}</h3><span>Customer ID: {record.customer_id}</span></div></div><span className="source-badge">{record.source==='shopify'?'Shopify · verified event':'Stripe · verified event'}</span>{record.context.email_status&&<p className="inspector-note">{record.context.email_status==='accepted'?'The provider accepted the test email. It was addressed to the configured test recipient; delivery is not yet verified.':'The test email was not accepted. Check the email connection.'}</p>}<section><h3>Observed event</h3><code className="event-code">{signalLabel(record.signal)}</code><div className="context-list">{Object.entries(record.context).map(([k,v])=><div key={k}><span>{contextLabel(k)}</span><strong>{contextValue(k,v)}</strong></div>)}</div></section><section><h3>Recommended next step</h3><small>{record.decision.engine==='gemini'?'Gemini · AI analysis':'Rule-based decision'}</small><div className="recommendation"><FileText size={20}/><div><strong>{record.decision.title}</strong><p>{record.decision.reason}</p></div></div></section>
 {record.status!=='resolved'&&<Button variant="outline" className="full-button" disabled={busy} onClick={()=>act('analyze')}>{busy?'Working…':'Run AI analysis'}</Button>}
 {record.status==='pending'?<Button className="full-button" disabled={busy} onClick={()=>act('execute')}><Play size={15}/>{busy?'Preparing…':'Prepare message draft'}</Button>:<section className="intervention"><h3><MessageSquare size={17}/> Prepared response</h3><p>{record.decision.message}</p><small>{record.decision.execution} {record.context.email_status==='accepted'?'The provider accepted the test email.':'No external message has been sent.'}</small>{record.ticket&&<code className="ticket">{record.ticket}</code>}{record.status==='resolved'?<div className="resolved-note"><CheckCircle2 size={16}/> An operator marked this issue as resolved.</div>:<><div className="feedback-actions"><Button variant="outline" disabled={busy} onClick={()=>act('resolve')}>Resolved</Button>{record.status!=='escalated'&&<Button variant="outline" disabled={busy} onClick={()=>act('escalate')}>Escalate to support</Button>}</div>{record.status==='active'&&record.decision.tool==='ask_user'&&<div className="reply-form"><label htmlFor="customer-reply">Received customer reply</label><Textarea id="customer-reply" maxLength={1000} placeholder="Record the customer reply…" value={reply} onChange={e=>setReply(e.target.value)}/><Button disabled={busy||!reply.trim()} onClick={()=>act('reply')}>Save reply</Button></div>}</>}</section>}
 {error&&<p className="error-box" role="alert">{error}</p>}<div className="inspector-note"><ShieldCheck size={16}/><span>Decisions should be grounded in the available source data.</span></div></aside>
}
