"use client";
import { useState } from 'react';
import { Plug, ExternalLink, ShieldCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from '@/components/ui/dialog';
export type ConnectionData={providers:{id:string;configured:boolean;domain:string|null;stats:{count:number;last_event:string}|null}[];events:{id:string;provider:string;event_type:string;customer_id:string;mode:string;created_at:string}[]};
export default function Integrations({data}:{data:ConnectionData|null}){
 const [setup,setSetup]=useState<string|null>(null);
 return <><div className="connection-grid">{['shopify','stripe'].map(id=>{const p=data?.providers.find(x=>x.id===id);return <article className="connection-card" key={id}><div className={`provider-mark ${id}`}>{id==='shopify'?'S':'s'}</div><h2>{id==='shopify'?'Shopify':'Stripe'}</h2><span className={`status ${p?.configured&&p.stats?'resolved':'pending'}`}>{p?.configured?(p.stats?'Verified event received':'Waiting for first event'):'Not connected'}</span><p>{id==='shopify'?'Cancelled test orders are sent automatically to the agent.':'The webhook receiver supports test payment failures and subscription events.'}</p>{p?.stats&&<p>{p.stats.count} events · {new Date(p.stats.last_event).toLocaleString('en-US')}</p>}<Button variant="outline" onClick={()=>setSetup(id)}><Plug size={16}/>Setup instructions</Button></article>})}</div><div className="integration-summary"><ShieldCheck size={18}/><p>Webhook signatures are verified and duplicate events are ignored. Only test events are accepted. Shopify customer sync and restricted test email are available; full activity history and customer delivery are not yet implemented.</p></div>
 <Dialog open={!!setup} onOpenChange={v=>{if(!v)setSetup(null)}}><DialogContent className="import-modal"><DialogHeader><DialogTitle>{setup==='shopify'?'Shopify':'Stripe'} connection</DialogTitle><DialogDescription>Configure the service before expecting verified events from it.</DialogDescription></DialogHeader>{setup==='shopify'?<ol className="setup-steps"><li>Open <a href="https://dev.shopify.com/" target="_blank" rel="noreferrer">Shopify Dev Dashboard</a> to create an account and development store.</li><li>Create an app, grant the required order permissions, and install it on the store.</li><li>Add the app secret and store <code>myshopify.com</code> domain to the secure server configuration.</li><li>Subscribe to <code>orders/cancelled</code> events to the public HTTPS endpoint <code>/api/webhooks/shopify</code>.</li><li>Create and cancel a test order. Check the event log for the result.</li></ol>:<ol className="setup-steps"><li>Open <a href="https://dashboard.stripe.com/" target="_blank" rel="noreferrer">Stripe Dashboard</a> to open your test environment.</li><li>Subscribe to <code>invoice.payment_failed</code>, <code>customer.subscription.deleted</code> and <code>customer.subscription.trial_will_end</code> events.</li><li>Webhook endpoint on your public HTTPS server: <code>/api/webhooks/stripe</code>. You can use Stripe CLI forwarding for local testing.</li><li>Add the webhook signing secret to the secure server configuration.</li><li>Create a test event and confirm it appears in the log.</li></ol>}<p className="notice">A localhost address is only accessible on this computer. Webhooks require a configured public HTTPS endpoint.</p></DialogContent></Dialog></>
}
