"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Activity,Check,CheckCircle2,Clock3,Mail,Play,RotateCcw,Search,ShieldCheck,Sparkles,TrendingDown,AlertCircle,ChevronRight,LoaderCircle} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {outreachBlock,type RetentionProfile,type Policy} from '@/lib/retention-core';
import './retention.css';
import JudgeGuide from './judge-guide';
import {judgeCase} from '@/lib/demo-guide';
const actionLabel:Record<string,string>={checkout_recovery:'Recover the checkout',cart_recovery:'Help with the cart',post_cancellation_followup:'Offer cancellation support',reengagement:'Reconnect thoughtfully',troubleshoot:'Restore the integration',onboarding_help:'Help complete onboarding',billing_help:'Help resolve the payment',clarify:'Ask a focused question',internal_review:'Internal review only',no_action:'Monitor without outreach'};
const time=(value:string)=>new Date(value).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});
async function request<T=RetentionProfile>(body:unknown,endpoint:string){const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json() as T & {error?:string};if(!r.ok)throw Error(data.error||'The action could not be completed.');return data;}
export default function Retention({judge=false}:{judge?:boolean}){
 const endpoint=judge?'/api/judge':'/api/retention';
 const [profiles,setProfiles]=useState<RetentionProfile[]>([]),[selected,setSelected]=useState<string|null>(null),[busy,setBusy]=useState(''),[error,setError]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[loaded,setLoaded]=useState(false),[policyOpen,setPolicyOpen]=useState(false),[storageUnavailable,setStorageUnavailable]=useState(false);
 const sequence=useRef(0);
 const load=useCallback(async()=>{const seq=++sequence.current;const r=await fetch(endpoint);const data=await r.json() as {profiles:RetentionProfile[];error?:string};if(!r.ok){if(seq===sequence.current)setStorageUnavailable(r.status===503);throw Error(data.error||'Could not load retention profiles.');}if(seq===sequence.current){setProfiles(data.profiles);setLoaded(true);setStorageUnavailable(false);setError(previous=>previous.startsWith('Storage is temporarily unavailable')?'':previous);}},[endpoint]);
 useEffect(()=>{void load().catch(e=>{setError(e.message);setLoaded(true)});},[load]);
 useEffect(()=>{if(busy)return;const timer=setInterval(()=>{if(!document.hidden)void load().catch(()=>{});},10000);return()=>clearInterval(timer);},[load,busy]);
 const p=profiles.find(p=>p.account.id===selected);
 async function act(action:string){if(busy)return;setBusy(action);setError('');try{const data=await request({action,...(p&&!['start_demo','reset_demo'].includes(action)?{id:p.account.id,version:p.account.version}:{})},endpoint);await load();setSelected(action==='start_demo'&&!judge?'demo:northstar':data.account.id);}catch(e){setError((e as Error).message);void load().catch(()=>{});}finally{setBusy('');}}
 async function updatePolicy(policy:Policy){setBusy('policy');setError('');try{await request({action:'policy',policy},endpoint);await load();}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 const demo=profiles.find(p=>judge?p.account.id.endsWith(':checkout'):p.account.id==='demo:northstar'),shown=profiles.filter(p=>(filter==='all'||p.account.source===filter)&&(p.account.name.toLowerCase().includes(query.toLowerCase())||(p.account.email||'').toLowerCase().includes(query.toLowerCase())));
 const currentAction=p?.actions.find(a=>a.decisionId===p.decision?.id);
 const decision=p?.decision?.diagnosis,block=p?outreachBlock(p.account,p.actions,new Date(),p.policy):null,stale=p?.decision&&p.decision.fingerprint!==p.fingerprint;
 const scenario=judge&&p?judgeCase(p.account.id):undefined;
 const completed=p?.actions.some(a=>a.approvedBy!=='seeded-demo'&&['simulated','accepted'].includes(a.status)),improved=p&&p.events.some(e=>['usage_recovered','checkout_recovered'].includes(e.kind)&&e.id.includes(':reengaged:'));
 return <div className="rt">
 <div className="rt-top"><div><h1>{p?p.account.name:judge?'Shopify retention demo':'Retention workspace'}</h1><p>{p?'Understand the evidence. Choose the next useful step.':'See shopping activity. Choose a useful next step.'}</p></div><div className="rt-top-actions">{p?<Button variant="outline" onClick={()=>{setSelected(null);setError('')}}><ArrowLeft size={15}/>All customers</Button>:null}<Button disabled={!!busy} onClick={()=>act('start_demo')}><Play size={15}/>{demo?'Open judge demo':'Start judge demo'}</Button></div></div>
 {judge?<JudgeGuide/>:null}
 {error?<div role="alert" className="error-box"><p>{error}</p>{storageUnavailable?<p>The interactive demo cannot start until the owner connects the hosted database. No password is needed. You can still explore the fictional data above.</p>:null}</div>:null}
 {!p?<>
 <div className="rt-overview"><div><span>Customers in this workspace</span><strong>{storageUnavailable?'—':profiles.length}</strong><small>{storageUnavailable?'Unavailable until storage connects':`${profiles.filter(p=>p.account.source==='shopify').length} Shopify · ${profiles.filter(p=>p.account.source==='demo').length} synthetic`}</small></div><div><span>Need attention</span><strong>{storageUnavailable?'—':profiles.filter(p=>['High','Moderate'].includes(p.risk.level)).length}</strong><small>Based on unresolved event evidence</small></div><div><span>Approval & delivery</span><strong>Controlled</strong><small>Manual by default · merchant policy enforced</small></div></div>
 <div className="rt-demo-callout"><span className="rt-demo-icon"><Sparkles size={24}/></span><div><h2>See cause-aware retention in action</h2><p>{judge?'Ava viewed Trail Shoes, added them to the cart, and left checkout incomplete. Review the context, analyze with Gemini, and simulate a recovery intervention.':'Northstar’s usage fell after three integration failures. Diagnose the issue, approve a response, and simulate recovery.'}</p><small>Clearly labelled synthetic data. A simulated outcome is not proof of retention.</small></div><button disabled={!!busy} onClick={()=>act('start_demo')} aria-label={judge?"Open Ava shopping demo":"Open Northstar demo"}><ArrowRight size={20}/></button></div>
 <div className="rt-toolbar"><div className="rt-search"><Search size={17}/><Input placeholder="Search customers…" aria-label="Search retention customers" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="rt-filters" role="group" aria-label="Customer source">{[['all','All'],['shopify','Shopify'],['demo','Synthetic demo']].map(([v,label])=><button key={v} aria-pressed={filter===v} onClick={()=>setFilter(v)}>{label}</button>)}</div></div>
 <div className="rt-list"><div className="rt-list-head"><span>Customer</span><span>Risk & evidence</span><span>Next step</span></div>{shown.map(profile=><button className="rt-account-row" key={profile.account.id} onClick={()=>{setSelected(profile.account.id);setError('')}}><div className="rt-account"><span className="rt-avatar">{profile.account.name.slice(0,2).toUpperCase()}</span><div><strong>{profile.account.name}</strong><small>{profile.account.source==='demo'?'Synthetic demo':profile.account.email||'Email unavailable'}</small></div></div><div><span className={`rt-risk-tag ${profile.risk.level.toLowerCase()}`}>{profile.risk.level==='Unknown'?'Insufficient data':`${profile.risk.level} · ${profile.risk.score}`}</span><small>{profile.risk.evidence[0]?.label||profile.risk.summary}</small></div><div><span>{profile.events.some(e=>e.id.includes(':reengaged:'))?'Simulated outcome recorded':profile.decision?actionLabel[profile.decision.diagnosis.action]:'Ready for analysis'}</span><ChevronRight size={17}/></div></button>)}{!shown.length?<div className="rt-empty">{!loaded?'Loading customer evidence…':query?'No customers match this search.':storageUnavailable?'Customer counts are unavailable while storage is offline.':judge?'Start the judge demo to load seven fictional customers.':'No customer profiles yet. Sync Shopify customers or start the judge demo.'}</div>:null}</div>
 </>:<>
 {scenario?<section className="rt-panel rt-case-explainer"><h2>{scenario.title}</h2><p>{scenario.story}</p><p><strong>Expected response: {scenario.expectedLabel}.</strong> {scenario.reason}</p><small>This is a fictional teaching example. The actual recommendation appears after analysis.</small></section>:null}
 <div className="rt-profile-meta"><span className={`rt-source ${p.account.source}`}>{p.account.source==='demo'?'Synthetic demonstration':'Shopify · synchronized record'}</span><span>{p.account.email||'Email unavailable'}</span><span><ShieldCheck size={14}/>{p.account.profile.emailConsent==='allowed'?p.account.source==='demo'?'Synthetic permission':'Email permission recorded':p.account.profile.emailConsent==='opted_out'?'Email opted out':'Communication permission unavailable'}</span></div>
 {p.account.source==='demo'?<div className="rt-demo-progress"><div className={!decision?'current':'done'}><span>1</span>Review evidence</div><div className={decision?'done':''}><span>2</span>AI diagnosis</div><div className={completed?'done':decision?'current':''}><span>3</span>Approve & execute</div><div className={improved?'done':completed?'current':''}><span>4</span>Simulate outcome</div><Button variant="ghost" size="sm" disabled={!!busy} onClick={()=>act('reset_demo')}><RotateCcw size={14}/>Reset demo</Button></div>:null}
 {improved?<div className="rt-result-banner"><span><CheckCircle2 size={22}/></span><div><strong>Simulated recovery recorded</strong><p>New synthetic activity resolved the documented signals. This is not proof of actual customer retention.</p></div><div className="rt-result-score"><b>{p.baseline}</b><ArrowRight size={20}/><strong>{p.risk.score}</strong></div></div>:null}
 <div className="rt-profile-grid"><div className="rt-left">
 <section className="rt-panel rt-risk-panel"><div className="rt-section-head"><h2>Current risk</h2><span>Evidence-based heuristic</span></div><div className="rt-risk-summary"><div className={`rt-score ${p.risk.level.toLowerCase()}`} style={{'--score':`${p.risk.score}%`} as React.CSSProperties}><strong>{p.risk.level==='Unknown'?'—':p.risk.score}</strong><small>/ 100</small></div><div><h3>{p.risk.level==='Unknown'?'Not enough activity data':`${p.risk.level} risk`}</h3><p>{p.risk.summary}</p><small>This score prioritizes attention. It is not a probability of churn.</small></div></div><div className="rt-evidence">{p.risk.evidence.map((e,i)=><div key={`${e.eventId}-${i}`}><AlertCircle size={14}/><span>{e.label}</span><strong>+{e.points}</strong></div>)}{!p.risk.evidence.length?<p>No unresolved risk evidence in the available history.</p>:null}</div></section>
 <section className="rt-panel"><div className="rt-section-head"><h2>Customer context</h2></div><dl className="rt-context"><div><dt>Plan / subscription</dt><dd>{p.account.profile.plan||'Unavailable from synchronized source'}</dd></div><div><dt>Monthly value</dt><dd>{p.account.profile.mrr===null?'Unavailable':`$${p.account.profile.mrr} · synthetic`}</dd></div><div><dt>Purchase history</dt><dd>{p.account.profile.purchase||(p.account.source==='demo'?'Not supplied in this demo scenario':'Unavailable from synchronized source')}</dd></div><div><dt>Onboarding</dt><dd>{p.account.profile.onboarding||'Unavailable from synchronized source'}</dd></div><div><dt>Usage / billing / support</dt><dd>{p.account.source==='demo'?'Available in the synthetic event timeline':'Unavailable unless included in synchronized events'}</dd></div></dl></section>
 <section className="rt-panel"><div className="rt-section-head"><h2>Activity timeline</h2><span>{p.events.length} {p.account.source==='demo'?'fictional':'observed'} event{p.events.length===1?'':'s'}</span></div><p className="rt-muted">Newest event first. Times use your browser’s local time zone. Viewing a product alone does not establish a retention problem.</p><ol className="rt-timeline">{[...p.events].reverse().map(e=><li key={e.id}><span className={`rt-timeline-dot ${e.id.includes(':reengaged:')?'green':''}`}><Activity size={13}/></span><div><strong>{e.summary}</strong><small>{time(e.at)} · {e.synthetic?'Fictional event':'Shopify event'}</small>{e.synthetic?<details className="rt-event-data"><summary>Inspect event data</summary><pre>{JSON.stringify({kind:e.kind,at:e.at,synthetic:e.synthetic,data:e.data},null,2)}</pre></details>:null}</div></li>)}</ol>{!p.events.length?<p className="rt-muted">No activity is available. Resolve will not invent usage or a churn cause.</p>:null}</section>
 </div><div className="rt-right">
 <section className="rt-panel rt-agent"><div className="rt-section-head"><h2><Sparkles size={18}/>Resolve agent</h2><span>{decision?.engine==='gemini'?(currentAction?'Gemini · prior diagnosis':'Live Gemini'):decision?'Deterministic fallback':'Ready'}</span></div>{decision?<>
 {decision.fallbackReason?<p className="rt-fallback">{decision.fallbackReason}</p>:null}
 {stale&&!currentAction?<p className="rt-warning">Evidence or policy changed. This diagnosis is historical; run analysis again before acting.</p>:null}
 <h3>{actionLabel[decision.action]}</h3><div className="rt-diagnosis"><small>POSSIBLE CAUSE</small><p>{decision.cause}</p><small>WHY THIS ACTION</small><p>{decision.explanation}</p><small>WHAT WE DON’T KNOW</small><p>{decision.uncertainty}</p></div>
 <details className="rt-cited"><summary>View cited evidence ({decision.evidenceIds.length})</summary>{decision.evidenceIds.map(id=><p key={id}>{p.events.find(e=>e.id===id)?.summary||'Event unavailable'}</p>)}</details>
 </>:<div className="rt-agent-empty"><Sparkles size={28}/><h3>Understand the underlying problem</h3><p>The agent reviews actual events, previous outreach, and communication permissions before recommending a response.</p></div>}
 <Button variant={decision?'outline':'default'} className="rt-full" disabled={!!busy} onClick={()=>act('analyze')}>{busy==='analyze'?<LoaderCircle size={16} className="spin"/>:<Sparkles size={16}/>} {busy==='analyze'?'Analyzing customer context…':decision?'Analyze again':'Analyze with AI'}</Button>
 </section>
 {decision?.message?<section className="rt-panel rt-email"><div className="rt-section-head"><h2><Mail size={17}/>Personalized response</h2><span>{currentAction?'Approved response':'Draft'}</span></div><div className="rt-email-address"><small>TO</small><span>{p.policy.mode==='simulation'?'In-app simulator · no email sent':'Configured test recipient only'}</span></div><h3>{decision.subject}</h3><p className="rt-email-body">{decision.message}</p>{block&&!currentAction?<p className="rt-warning">{block}</p>:null}<Button className="rt-full" disabled={!!busy||!!block||!!stale||p.actions.some(a=>a.decisionId===p.decision?.id)} onClick={()=>act('approve')}>{busy==='approve'?<LoaderCircle size={16} className="spin"/>:<Check size={16}/>} {busy==='approve'?'Recording execution…':currentAction?'Execution recorded':p.policy.mode==='simulation'?'Approve & simulate delivery':p.policy.mode==='test_email'?'Approve & send test email':'Approve & send customer email'}</Button><p className="rt-muted">{currentAction?'This response is recorded in the intervention history.':p.policy.automatic?'Explicit automation is enabled for this demo workspace.':'Your approval is required before execution.'}</p></section>:null}
 {p.actions.length?<section className="rt-panel"><div className="rt-section-head"><h2>Intervention history</h2></div>{p.actions.map(a=><article className="rt-action" key={a.id}><div><span className={`rt-outcome ${a.status}`}>{a.status==='simulated'?'Simulated delivery':a.status==='accepted'?'Provider accepted · delivery unconfirmed':a.status==='unknown'?'Acceptance unknown':a.status==='executing'?'Execution in progress':a.status}</span></div><strong>{a.subject}</strong><small>{time(a.createdAt)} · {a.approvedBy==='operator'?'Operator approved':a.approvedBy==='seeded-demo'?'Seeded demo history':'Automatic policy'}</small>{a.error?<p>{a.error}</p>:null}</article>)}</section>:null}
 {completed&&p.account.source==='demo'?<section className={`rt-panel rt-outcome-panel ${improved?'complete':''}`}><div className="rt-section-head"><h2><TrendingDown size={18}/>Simulated outcome</h2></div>{improved?<><div className="rt-before-after"><div><small>BEFORE</small><strong>{p.baseline}</strong></div><ArrowRight/><div><small>AFTER NEW EVENTS</small><strong>{p.risk.score}</strong></div></div><p>New synthetic activity resolved the documented risk signals. This is a demo outcome, not proof that outreach caused retention.</p></>:<><p>Introduce a clearly synthetic successful outcome, then watch the evidence-based score change.</p><Button disabled={!!busy} className="rt-full" onClick={()=>act('reengage')}>{busy==='reengage'?<LoaderCircle className="spin" size={16}/>:<Activity size={16}/>}Simulate re-engagement</Button></>}</section>:null}
 </div></div>
 <section className="rt-panel rt-audit"><div className="rt-section-head"><h2>Action & audit trail</h2><span>Persisted in the database</span></div>{!p.audit.length?<p className="rt-muted">No retention actions have been recorded for this customer yet.</p>:null}{p.audit.map(a=><div key={a.id}><Clock3 size={14}/><span>{a.detail}</span><small>{time(a.at)}</small></div>)}</section>
 {p.account.source==='demo'&&!judge?<section className="rt-policy"><button onClick={()=>setPolicyOpen(!policyOpen)} aria-expanded={policyOpen}><ShieldCheck size={17}/><strong>Execution controls</strong><span>{p.policy.automatic?'Explicit automation enabled':'Manual approval'} · {p.policy.mode==='simulation'?'Simulator':'Restricted test email'}<ChevronRight size={15}/></span></button>{policyOpen?<div className="rt-policy-fields"><label><input type="checkbox" checked={p.policy.automatic} disabled={!!busy} onChange={e=>void updatePolicy({...p.policy,automatic:e.target.checked})}/>Automatically execute eligible recommendations after analysis</label><p>Demo workspace only. Opt-outs, a minimum 24-hour cooldown, evidence changes, and duplicate prevention still apply.</p><label>Delivery mode<select aria-label="Delivery mode" value={p.policy.mode} disabled={!!busy} onChange={e=>void updatePolicy({...p.policy,mode:e.target.value as Policy['mode']})}><option value="simulation">In-app simulation (no email)</option><option value="test_email" disabled={!p.capabilities.testEmail}>Restricted test email{!p.capabilities.testEmail?' (not configured)':''}</option></select></label><label>Minimum hours between outreach<input aria-label="Contact cooldown hours" type="number" min={24} max={168} defaultValue={p.policy.cooldownHours} key={p.policy.cooldownHours} disabled={!!busy} onBlur={e=>{const v=Number(e.target.value);if(v>=24&&v<=168&&Number.isInteger(v)&&v!==p.policy.cooldownHours)void updatePolicy({...p.policy,cooldownHours:v});else e.target.value=String(p.policy.cooldownHours)}}/></label><p>Changing policy makes an existing draft stale. Run analysis again to apply the updated controls.</p></div>:null}</section>:null}
 </>}
 </div>;
}
