'use client';
import {useEffect,useState} from 'react';
import {Activity,ArrowRight,CheckCircle2,Clock3,FileJson,Mail,RefreshCw,ShoppingBag,Wifi} from 'lucide-react';
import SiteHeader from './site-header';
import TestParticipant from './test-participant';
import OwnerResponse,{type OwnerRecovery} from './owner-response';
import ownerInitial from '@/public/owner-recovery.json';
import initial from '@/public/store-activity.json';
import previews from '@/public/store-responses.json';
import type {PublicActivity} from '@/lib/store-activity';
import '../../app/landing.css';
import './store-activity.css';
const labels:Record<string,string>={order_created:'Order placed',order_paid:'Payment confirmed',order_cancelled:'Order cancelled',refund_issued:'Refund recorded'};
const time=(at:string)=>new Date(at).toLocaleString('en-GB',{timeZone:'Asia/Baku',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false});
export default function StoreActivity(){
 const [dark,setDark]=useState(false),[data,setData]=useState<PublicActivity>(initial as PublicActivity),[refreshing,setRefreshing]=useState(false),[failed,setFailed]=useState(false),[recovery,setRecovery]=useState<OwnerRecovery>(ownerInitial as OwnerRecovery);
 async function refresh(signal?:AbortSignal){setRefreshing(true);void fetch('/owner-recovery.json',{cache:'no-store',signal}).then(r=>r.ok?r.json() as Promise<OwnerRecovery>:null).then(body=>{if(body?.version===1&&Array.isArray(body.responses))setRecovery(body)}).catch(()=>{});try{const r=await fetch('/api/public/activity',{cache:'no-store',signal});if(!r.ok)throw Error('Activity unavailable');const body=await r.json() as PublicActivity;if(!Array.isArray(body.records)||!body.checkedAt)throw Error('Invalid activity');setData(body);setFailed(false);}catch{if(!signal?.aborted)setFailed(true);}finally{if(!signal?.aborted)setRefreshing(false);}}
 useEffect(()=>{const controller=new AbortController();void refresh(controller.signal);const timer=setInterval(()=>{if(document.visibilityState==='visible')void refresh(controller.signal)},30000);return()=>{controller.abort();clearInterval(timer)}},[]);
 const ownerEmails=recovery.responses.filter(r=>['accepted','delivered'].includes(r.delivery.status)).length;
 const events=data.records.reduce((n,r)=>n+r.events.length,0),live=data.source==='live'&&!failed;
 return <div className={`rl ${dark?'rl-dark':''}`}><SiteHeader dark={dark} onTheme={()=>setDark(!dark)}/><main className="ra-workspace"><div className="ra-breadcrumb"><a href="/">Resolve</a><span>/</span>Customer activity</div><header className="ra-hero"><div><span className="rl-eyebrow"><span className="rl-dot"/> THE RETENTION WORKSPACE</span><h1>Every signal<br/><em>has a story.</em></h1><p>Shopify activity, the context behind it, and the next step — together in one place.</p></div><div className="ra-connection"><span className={live?'ra-state connected':'ra-state'}>{live?<Wifi size={15}/>:<Clock3 size={15}/>} {live?'Connected to Shopify':'Recorded Shopify activity'}</span><p>{live?'New test orders and cancellations refresh here automatically.':'Showing actual store records saved at the time below. Live updates are not connected.'}</p><small>Last Shopify read: {time(data.checkedAt)} · Baku</small><button onClick={()=>void refresh()} disabled={refreshing}><RefreshCw size={14} className={refreshing?'ra-spinning':''}/>{refreshing?'Checking…':'Check for updates'}</button>{failed?<small role="status">Refresh unavailable. Keeping the last confirmed records.</small>:null}</div></header>
 <TestParticipant records={data.records} live={live}/>
 <section className="ra-metrics" aria-label="Captured activity"><div><ShoppingBag size={18}/><strong>{data.records.length}</strong><span>Shopify test orders</span></div><div><Activity size={18}/><strong>{events}</strong><span>Recorded events</span></div><div><Mail size={18}/><strong>{ownerEmails}</strong><span>Owner cancellation emails accepted</span></div></section>
 <section className="ra-stream"><div className="ra-section-heading"><div><span className="rl-eyebrow">ACTIVITY STREAM</span><h2>What actually happened.</h2></div><span className="ra-source"><CheckCircle2 size={14}/>Shopify Admin API · test payments</span></div><p className="ra-caption">Only actual test orders from the connected store appear here. Customer names, email addresses and delivery addresses are withheld.</p>
 {data.records.length===0?<div className="ra-empty">No Shopify test orders have been captured. Place an order using the store’s test payment gateway, then check for updates once the live connection is available.</div>:data.records.map(order=>{const ownerResponse=recovery.responses.find(r=>r.reference===order.reference&&r.participantId===order.participantId);const response=previews.responses.find(r=>r.reference===order.reference&&r.orderUpdatedAt===order.updatedAt);return <article className="ra-order" key={order.reference}><div className="ra-order-top"><div><span className="ra-order-ref">{order.reference}</span><p className="ra-order-customer">Shopify customer ID: {order.customerId||'Unavailable'}{order.participantId?' · Registered test customer':' · Not matched to the registered participant'}</p><h3>{order.products.map(p=>`${p.title} × ${p.quantity}`).join(', ')||'Product details unavailable'}</h3><p>{order.currency} {order.amount} <span>Shopify test order · no live payment</span></p></div><span className={order.cancelled?'ra-status cancelled':'ra-status'}>{order.cancelled?'Cancelled':order.status.replaceAll('_',' ').toLowerCase()}</span></div><div className="ra-order-grid"><div><h4>Observed timeline</h4><ol className="ra-timeline">{order.events.map((event,i)=><li key={`${event.kind}-${i}`}><span className="ra-timeline-dot"/><div><strong>{labels[event.kind]||event.kind}</strong><p>{event.summary}</p><small>{time(event.at)} · Baku</small></div></li>)}</ol></div><div className="ra-next"><div className="ra-next-icon"><Mail size={20}/></div><h4>{order.cancelled?'A cancellation deserves context.':'A completed order needs no recovery.'}</h4><p>{order.cancelled?ownerResponse?'The cancellation triggered the enrolled owner’s support workflow. Its reason code alone does not explain the shopper’s motive.':'Shopify recorded the cancellation. Its reason code alone does not explain the shopper’s motive. No support-email receipt is recorded for this order.':'The store recorded this purchase. We do not create an abandonment story or recovery message for a completed order.'}</p>{ownerResponse?<OwnerResponse response={ownerResponse}/>:response?<div className="ra-response"><span className="ra-response-tag">Gemini · operator test preview</span><strong>{response.subject}</strong><p className="ra-response-body">{response.message}</p><details><summary>Response context</summary><p>{response.explanation}</p><p>{response.uncertainty}</p><small>Generated {time(response.generatedAt)} · Baku</small></details><span className="ra-message-state">{response.delivery.note}</span></div>:<span className="ra-message-state">No sent message recorded</span>}</div></div><details className="ra-log"><summary><FileJson size={15}/>View source record</summary><pre>{JSON.stringify(order,null,2)}</pre></details></article>})}
 </section><section className="ra-coverage"><div><span className="rl-eyebrow">CONNECTION COVERAGE</span><h2>Show the evidence.<br/><em>Leave the unknowns open.</em></h2><p>An unconnected event is not an abandoned journey. New browsing and cart activity need a storefront collector; email delivery needs its own verified workflow.</p></div><dl><div><dt>Orders & cancellations</dt><dd>{live?'Connected · refreshes every 30 seconds':'Saved records · live connection pending'}</dd></div><div><dt>Product browsing</dt><dd>Not connected · no events invented</dd></div><div><dt>Cart activity</dt><dd>Not connected · no events invented</dd></div><div><dt>Cancellation email</dt><dd>Owner trial only · local agent · {ownerEmails} accepted receipt(s)</dd></div></dl></section><footer className="ra-footer"><a href="/guide">Connection instructions <ArrowRight size={15}/></a><a href="/store-activity.json" download>Download saved records <FileJson size={15}/></a><span>Actual Shopify records. No generated shopper histories.</span></footer></main></div>;
}
