import Link from 'next/link';
import {ArrowDown,ArrowRight,CheckCircle2,FileJson,Footprints,Mail,ShoppingBag,Sparkles,Undo2} from 'lucide-react';
import evidence from '@/public/submission-evidence.json';
import './submission-walkthrough.css';
const names:Record<string,string>={browsing_followup:'Offer product help',cart_recovery:'Help with the cart',post_cancellation_followup:'Offer cancellation support'};
export default function SubmissionWalkthrough(){
 const accepted=evidence.scenarios.filter(s=>s.delivery.status==='accepted').length;
 const generated=evidence.scenarios.every(s=>s.analysis.engine==='gemini');
 return <main className="sw-page">
  <nav className="sw-nav"><Link className="sw-logo" href="/">resolve<span>.</span></Link><span>Judge walkthrough</span><Link href="/guide">How it works <ArrowRight size={14}/></Link></nav>
  <header className="sw-hero"><div className="sw-eyebrow"><span/> A retention agent that acts on context</div><h1>Three exits.<br/><span>Three thoughtful responses.</span></h1><p>A shopper browses and leaves, abandons a cart, or cancels an order. Resolve records the context and prepares a different, helpful message for each.</p><div className="sw-tags"><span>Synthetic shopping scenarios</span><span>{generated?'Recorded Gemini drafts':'Authored example drafts'}</span><span>No judge login or setup</span></div>
   <div className="sw-summary"><div><strong>03</strong><span>Different shopping journeys</span></div><div><strong>03</strong><span>Inspectable email drafts</span></div><div><strong>{String(accepted).padStart(2,'0')}</strong><span>Test previews accepted by provider</span></div></div>
  </header>
  <section className="sw-intro" aria-label="Read this first"><Sparkles size={23}/><div><strong>Everything is already here. Just scroll.</strong><p>These are recorded examples, not real Shopify tracking receipts. {generated?'Gemini generated the drafts from the fictional evidence.':'The drafts are authored examples.'} {accepted?'The accepted test previews went only to the operator’s configured inbox; inbox delivery is not yet verified.':'No confirmed test email acceptance is recorded.'} Browsing does not establish dissatisfaction.</p></div><a href="#browse" aria-label="See the first scenario"><ArrowDown size={20}/></a></section>
  <div className="sw-jumps" aria-label="Jump to a scenario"><a href="#browse"><Footprints size={17}/>01 · Just browsing</a><a href="#cart"><ShoppingBag size={17}/>02 · An unfinished cart</a><a href="#cancel"><Undo2 size={17}/>03 · A cancelled order</a></div>
  {evidence.scenarios.map((scenario,index)=><section className="sw-scenario" id={scenario.id} key={scenario.id} aria-label={scenario.label}>
   <div className="sw-scenario-heading"><span className="sw-number">0{index+1}</span><div><p className="sw-overline">{scenario.product} · fictional item</p><h2>{scenario.label}</h2></div><span className="sw-auto"><Sparkles size={13}/>Different response, same workflow</span></div>
   <p className="sw-signal">{scenario.signal}</p>
   <div className="sw-scenario-grid"><div className="sw-observation"><h3><span>1</span>What happened</h3><ol className="sw-timeline">{scenario.events.map(event=><li key={event.id}><span className="sw-timeline-dot"/><div><strong>{event.summary}</strong><small>{event.at.slice(11,16)} UTC · {event.kind.replaceAll('_',' ')}</small></div></li>)}</ol>
    <div className="sw-analysis"><div><Sparkles size={16}/><strong>2 · {names[scenario.analysis.action]||scenario.analysis.action}</strong><span>{scenario.analysis.engine==='gemini'?'Gemini':'Example'}</span></div><p>{scenario.analysis.explanation}</p><details><summary>Why this response? See the uncertainty.</summary><p><strong>Possible interpretation:</strong> {scenario.analysis.cause}</p><p><strong>Still unknown:</strong> {scenario.analysis.uncertainty}</p><p>Evidence cited: {scenario.analysis.evidenceIds.join(', ')}.</p></details></div>
    <p className="sw-permission">Fictional signed-in shopper · email permission allowed.{scenario.id==='browse'?' This example explicitly opts into browsing help; default merchant behavior is observe-only.':''}</p>
   </div><div className="sw-mail"><div className="sw-mail-heading"><span className="sw-mail-icon"><Mail size={20}/></span><div><h3>3 · The customer message</h3><p>A prepared preview, ready to inspect</p></div></div><div className="sw-mail-envelope"><p><span>To</span>Configured operator test inbox · address withheld</p><p><span>Subject</span><strong>{scenario.analysis.subject}</strong></p></div><div className="sw-mail-body">{scenario.analysis.message}</div><div className={`sw-delivery ${scenario.delivery.status==='accepted'?'sw-accepted':''}`}><CheckCircle2 size={16}/><div><strong>{scenario.delivery.status==='accepted'?'Test preview accepted by Resend':'Message content available'}</strong><p>{scenario.delivery.note}</p>{scenario.delivery.checkedAt?<small>{scenario.delivery.checkedAt.replace('T',' ').replace(/\.\d+Z$/,' UTC')}</small>:null}</div></div></div></div>
   <details className="sw-raw"><summary><FileJson size={16}/>Inspect this scenario’s event and decision log</summary><pre>{JSON.stringify(scenario,null,2)}</pre></details>
  </section>)}
  <section className="sw-flow"><div><p className="sw-overline">The product idea</p><h2>Understand the signal.<br/>Help with the right thing.</h2><p>The intended live workflow connects Shopify events to an identified customer, lets Gemini interpret the evidence, checks messaging permission, then sends and records the response.</p></div><ol><li><span>01</span><strong>Capture activity</strong><p>Record observed events with time and source.</p></li><li><span>02</span><strong>Choose a response</strong><p>Separate what happened from what is still unknown.</p></li><li><span>03</span><strong>Send & record</strong><p>Check consent and contact limits. Save the draft and provider status.</p></li></ol></section>
  <footer className="sw-footer"><p><strong>Honest demo boundary:</strong> this page is a saved walkthrough of synthetic behavior. Test previews, if accepted, are real emails from those examples. It does not claim continuous live Shopify tracking or automatic customer delivery.</p><div><a href="/submission-evidence.json" download>Download the full evidence JSON <FileJson size={14}/></a><Link href="/demo/ai">Optional interactive AI sandbox <ArrowRight size={14}/></Link><Link href="/guide">Judge instructions</Link></div></footer>
 </main>;
}
