import {CheckCircle2,Mail,UserRound} from 'lucide-react';
import participant from '@/public/test-participant.json';
import type {PublicActivity} from '@/lib/store-activity';
export default function TestParticipant({records,live}:{records:PublicActivity['records'];live:boolean}){
 const matched=records.filter(r=>r.participantId===participant.id);
 const customerId=matched.find(r=>r.customerId)?.customerId;
 const emailStatus=participant.email.status==='delivered'?'Delivery confirmed by Resend':participant.email.status==='accepted'?'Accepted by Resend':'Delivery unconfirmed';
 return <section className="ra-participant" aria-label="Registered test customer"><div className="ra-participant-top"><span className="rl-eyebrow"><UserRound size={15}/> REGISTERED TEST CUSTOMER</span><span className="ra-status">Actual database record</span></div><h2>Your customer profile.</h2><p className="ra-caption">A real participant, registered with explicit permission. Contact details remain private.</p><div className="ra-participant-grid"><div><small>Resolve customer ID</small><strong className="ra-customer-id">{participant.id}</strong><small>Shopify customer ID</small><strong>{customerId||'Waiting for an email-matched test order'}</strong><small>Observed situation</small><p>{matched.some(r=>r.cancelled)?'A matched order was cancelled. The underlying cause is still unknown.':matched.length?'A test purchase was observed. Dissatisfaction has not been established.':'No matched shopping problem yet. We do not assume dissatisfaction.'}</p><small>Stored in Resolve</small><p>{participant.storage}. Shopify history is matched only when the checkout email equals the registered address.</p></div><div className="ra-participant-email"><span className="ra-response-tag"><Mail size={14}/> REGISTRATION EMAIL · NOT A RECOVERY MESSAGE</span><strong>{participant.email.subject}</strong><p className="ra-response-body">{participant.email.message}</p><span className="ra-state"><CheckCircle2 size={14}/>{emailStatus}</span><p>{participant.email.note}</p><small>{new Date(participant.email.createdAt).toLocaleString('en-GB',{timeZone:'Asia/Baku',dateStyle:'medium',timeStyle:'short'})} · Baku</small></div></div><div className="ra-participant-next">{live?'Next: use your registered email at Shopify test checkout. Matching test orders refresh here automatically.':'Next: connect the existing Shopify values on Vercel. Then use your registered email at Shopify test checkout.'} Product browsing and cart tracking are not yet connected.</div></section>;
}
