import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {analyzeWithGemini,RETENTION_MODEL,RETENTION_PROMPT_VERSION} from '../lib/retention-gemini.ts';
import {evaluationScenarios} from './evaluation-scenarios.mjs';
import {baselineDiagnosis,activeEvents,outreachBlock} from '../lib/retention-core.ts';
const root='hackathon-evidence/',now=new Date();
const scenarios=await evaluationScenarios(now);
const rubric={definedBeforeCalls:now.toISOString(),scenarios:scenarios.map(s=>({id:s.id,name:s.name,expected:s.expected,events:s.events,consent:s.profile.account.profile.emailConsent,recent:s.recent||false})),criteria:['Exact intervention category','No unsupported shipping, price, affordability or dissatisfaction claims','References only supplied evidence','Opt-out, recovered checkout and cooldown suppress outreach'],genericBaseline:'Respect permission and cooldown. Remind only an unresolved abandoned checkout; otherwise no_action. Opt-outs get internal_review.',productionBaseline:'Existing context-aware deterministic baselineDiagnosis, identical policy and input.'};
writeFileSync(root+'logs/evaluation-rubric.json',JSON.stringify(rubric,null,2)+'\n');
const variables=Object.fromEntries(readFileSync('.dev.vars','utf8').split(/\r?\n/).filter(v=>v.includes('=')&&!v.startsWith('#')).map(v=>{const i=v.indexOf('=');return [v.slice(0,i).trim(),v.slice(i+1).trim().replace(/^['"]|['"]$/g,'')]}));
const results=[];
for(const s of scenarios){const p=s.profile;const blocked=outreachBlock(p.account,p.actions,now,p.policy);const generic=blocked?(p.account.profile.emailConsent==='opted_out'?'internal_review':'no_action'):activeEvents(p.events).some(e=>e.kind==='checkout_abandoned')?'checkout_recovery':'no_action';const production=baselineDiagnosis(p.account,p.events,p.actions,now,p.policy);const start=performance.now();try{const ai=await analyzeWithGemini(p,variables.GEMINI_API_KEY||'',now);results.push({id:s.id,name:s.name,expected:s.expected,generic,productionBaseline:production.action,...ai,agreement:ai.diagnosis.action===s.expected,validEvidence:ai.diagnosis.evidenceIds.every(id=>p.events.some(e=>e.id===id)),status:'PASS'});}catch(error){results.push({id:s.id,name:s.name,expected:s.expected,generic,productionBaseline:production.action,status:'FAIL',error:error instanceof Error?error.message:'Unknown',durationMs:Math.round(performance.now()-start)});}writeFileSync(root+'logs/gemini-evaluation.json',JSON.stringify({at:now.toISOString(),model:RETENTION_MODEL,promptVersion:RETENTION_PROMPT_VERSION,promptSourceSha256:createHash('sha256').update(readFileSync('lib/retention-gemini.ts')).digest('hex'),rubric,results},null,2)+'\n');console.log(s.id,results.at(-1).status,results.at(-1).diagnosis?.action||results.at(-1).error);}
