import Link from 'next/link';
import './guide.css';
import {judgeCases} from '@/lib/demo-guide';
export default function Guide(){return <main className="resolve-guide" style={{maxWidth:900,margin:'auto',padding:'40px 24px',lineHeight:1.8}}><nav style={{display:'flex',gap:24,flexWrap:'wrap'}}><Link href="/">resolve.</Link><Link href="/demo">Open judge demo</Link><Link href="/dashboard">Merchant dashboard</Link></nav>
 <h1 style={{fontSize:'clamp(30px,5vw,46px)',lineHeight:1.2,marginTop:40}}>See what happened. Choose how to help.</h1><p>Resolve brings Shopify activity into a customer timeline and recommends a response from the available evidence. An incomplete checkout can warrant checkout help. Browsing alone does not mean a customer is unhappy.</p>
 <section id="demo"><h2>For judges: try the fictional demonstration</h2><p><strong>No account, password, Shopify access, or payment required.</strong> All profiles are fictional. Delivery and re-engagement are simulated.</p><ol><li>Open the judge demo and click <strong>Start judge demo</strong>.</li><li>Read Ava’s timeline: product viewed → added to cart → checkout started → incomplete checkout.</li><li>Click <strong>Analyze with AI</strong>. Read the possible cause, uncertainty, evidence, and draft. The engine label distinguishes Gemini from fallback rules.</li><li>Click <strong>Approve & simulate delivery</strong>. No real email is sent.</li><li>Click <strong>Simulate re-engagement</strong>. A fictional completed checkout changes the unresolved-risk score.</li><li>Reload to check saved history. Use <strong>All customers</strong> to compare the other cases.</li></ol><p>If storage is unavailable, the interactive workflow cannot run. Use <strong>Explore the fictional data</strong> on the demo page to inspect the read-only examples. This preview does not call AI or save interventions.</p></section>
 <section><h2>What each example teaches</h2><div style={{display:'grid',gap:12}}>{judgeCases.map(item=><article key={item.id} style={{border:'1px solid #e1dfed',borderRadius:12,padding:18}}><h3 style={{margin:0}}>{item.name} — {item.title}</h3><p>{item.story}</p><strong>{item.expectedLabel}</strong><p style={{marginBottom:0}}>{item.reason}</p></article>)}</div></section>
 <section id="shopify"><h2>For merchants: connect an actual Shopify store</h2><ol><li><strong>Connect and approve access.</strong> Install Resolve in your authorized store. Customer/order sync needs the appropriate scopes; browsing capture also requires the deployed pixel extension and pixel permissions.</li><li><strong>Connect persistent storage.</strong> The deployed app needs a managed database, its server-side credentials, and the SQL migrations. A laptop database cannot serve a Vercel deployment.</li><li><strong>Synchronize commerce records.</strong> Open Agent operations and choose Sync Shopify. Check source health for permission failures before treating an empty list as a successful sync.</li><li><strong>Activate storefront collection.</strong> In Shopify behavior tracking, prepare collector settings. A developer must deploy the Shopify Web Pixel and register those settings with Shopify. Preparation alone is not activation.</li><li><strong>Verify real behavior.</strong> In the development storefront, grant the required analytics and marketing consent, view a product, and add it to the cart. Refresh tracking status. Confirm event receipts, then test a purchase and cancellation using Shopify’s test payment gateway.</li><li><strong>Configure delivery separately.</strong> Start in simulation or a restricted test email mode. Real-customer sending needs verified sender details, communication eligibility, authenticated merchant access, and a tested scheduler.</li></ol><p>Orders use trusted Shopify customer identifiers. Public pixel reports remain anonymous and self-reported; browser IDs and email guesses are not treated as customer identity. Unknown email permission, opt-outs, recent contact, and completed purchases prevent inappropriate outreach.</p><p>The broader SaaS example is fictional. Live browsing capture, hosted unattended execution, and real inbox delivery require separate verification; this guide does not claim they are already activated.</p></section>
 <section><h2>Understand the results</h2><ul><li>The risk score prioritizes unresolved signals. It is not a probability of churn.</li><li>A recommendation is a suggested action, not proof of the customer’s motive.</li><li>Provider acceptance is not confirmed inbox delivery.</li><li>A later purchase does not establish that Resolve caused it.</li></ul></section>
 </main>}
