"use client";
import { recordTitle, signalLabel } from "@/lib/presentation";
import { useCallback, useEffect, useRef, useState } from 'react';
import { Users, FileText, History, Settings2, Upload, Search, Clock3, CheckCircle2, ChevronRight, RefreshCw, Database, FileSpreadsheet, CircleHelp, LifeBuoy, Menu } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger,useSidebar } from '@/components/ui/sidebar';
import { Table,TableHeader,TableBody,TableRow,TableHead,TableCell } from '@/components/ui/table';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import Integrations, {type ConnectionData} from '@/components/resolve/integrations';
import Customers from '@/components/resolve/customers';
import Retention from '@/components/resolve/retention';
import AgentOperations from '@/components/resolve/agent-operations';
import Inspector from '@/components/resolve/inspector';
import { STATUS,type RecoveryRecord } from '@/lib/recovery';
type ImportRow={id:string;filename:string;row_count:number;source:string;status:string;created_at:string};
type RecordsData={records:RecoveryRecord[];total:number;stats:{total:number;pending:number;resolved:number};error?:string};
const nav=[{id:'agent',label:'Agent operations',icon:Settings2},{id:'retention',label:'Retention',icon:Users},{id:'directory',label:'Customer directory',icon:Database},{id:'customers',label:'Customer events',icon:Users},{id:'strategies',label:'Strategies',icon:FileText},{id:'imports',label:'Event log',icon:History},{id:'settings',label:'Integrations',icon:Settings2}];
export default function Home(){
 const [view,setView]=useState('retention');const [importOpen,setImportOpen]=useState(false);const [query,setQuery]=useState('');const [status,setStatus]=useState('all');const [page,setPage]=useState(0);const [data,setData]=useState<RecordsData>({records:[],total:0,stats:{total:0,pending:0,resolved:0}});const [selected,setSelected]=useState<RecoveryRecord|null>(null);const [connections,setConnections]=useState<ConnectionData|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const sequence=useRef(0);const currentData=useRef(data);currentData.current=data;
 const refresh=useCallback(async()=>{const seq=++sequence.current;setLoading(true);try{const r=await fetch(`/api/records?q=${encodeURIComponent(query)}&status=${status}&page=${page}`);const d=await r.json() as RecordsData;if(!r.ok)throw Error(d.error);if(seq!==sequence.current)return;setData(d);setError('')}catch(e){if(seq===sequence.current)setError((e as Error).message)}finally{if(seq===sequence.current)setLoading(false)}},[query,status,page]);
 useEffect(()=>{const timer=setTimeout(()=>void refresh(),200);return()=>clearTimeout(timer)},[refresh]);
 useEffect(()=>{async function load(){try{const r=await fetch('/api/integrations');const d=await r.json() as ConnectionData & {error?:string};if(!r.ok)throw Error(d.error);setConnections(d)}catch(e){setError((e as Error).message)}}void load();const timer=setInterval(()=>{if(!document.hidden){void load();void refresh()}},10000);return()=>clearInterval(timer)},[refresh]);
 useEffect(()=>{const ctx=(document as unknown as {modelContext?:{registerTool:(t:unknown,o:unknown)=>void}}).modelContext;if(!ctx)return;const life=new AbortController();try{ctx.registerTool({name:'read_customer_records',description:'Read the currently displayed verified webhook customer records and actual database counts. No mutation.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>currentData.current},{signal:life.signal})}catch{}return()=>life.abort()},[]);
 function imported(){setQuery('');setStatus('all');setPage(0);setView('customers');void refresh()}
 const active=nav.find(n=>n.id===view)!;
 return <SidebarProvider style={{'--sidebar-width':'216px'} as React.CSSProperties}><Sidebar className="app-sidebar"><SidebarHeader><a className="wordmark" href="/"><span>R</span>Resolve</a></SidebarHeader><SidebarContent><SidebarMenu className="nav-menu">{nav.map(n=><DashboardNavItem key={n.id} item={n} active={view===n.id} onSelect={()=>{setView(n.id);setError('')}}/>)}</SidebarMenu></SidebarContent><SidebarFooter><div className="workspace"><span>R</span><div>Resolve workspace<small>Local workspace</small></div></div></SidebarFooter></Sidebar>
 <div className="app-main"><header className="app-header"><div className="breadcrumbs"><SidebarTrigger className="mobile-menu"/><span>Resolve</span><ChevronRight size={14}/><strong>{active.label}</strong></div><span className="header-caption">Customer recovery</span></header>
 <div className={`main-layout ${selected&&view==='customers'?'with-inspector':''}`}><main className="main-content">{!['retention','agent'].includes(view)&&<div className="page-title"><div><h1>{active.label}</h1><p>{view==='customers'?'From customer events to a relevant next step.':view==='imports'?'Events received automatically from connected services.':view==='strategies'?'Evidence-based actions with clear explanations.':view==='directory'?'Customers synced from your connected Shopify store.':'Connections and available capabilities.'}</p></div><Button className="import-button" onClick={()=>setView('settings')}><Settings2 size={17}/>Connect a service</Button></div>}
 {view==='retention'&&<Retention/>}
 {view==='agent'&&<AgentOperations/>}
 {error&&<p role="alert" className="error-box">{error}</p>}
 {view==='directory'&&<Customers/>}
 {view==='customers'&&<><div className="metrics"><div><Users/><span>Events<strong>{loading&&!data.stats.total?'—':data.stats.total||0}</strong></span></div><div><Clock3/><span>Needs review<strong>{data.stats.pending||0}</strong></span></div><div><CheckCircle2 className="green"/><span>Resolved<strong>{data.stats.resolved||0}</strong></span></div></div><div className="toolbar"><div className="search"><Search size={18}/><Input aria-label="Search customers" placeholder="Search customers" value={query} onChange={e=>{setQuery(e.target.value);setPage(0)}}/></div><Select value={status} onValueChange={v=>{setStatus(v);setPage(0)}}><SelectTrigger aria-label="Filter by status"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All statuses</SelectItem>{Object.entries(STATUS).map(([k,v])=><SelectItem value={k} key={k}>{v}</SelectItem>)}</SelectContent></Select><Button variant="outline" size="icon" aria-label="Refresh list" onClick={refresh}><RefreshCw size={16} className={loading?'spin':''}/></Button></div>
 <div className="customer-table"><Table><TableHeader><TableRow><TableHead>Customer</TableHead><TableHead>Signal</TableHead><TableHead>Strategy</TableHead><TableHead>Status</TableHead><TableHead><span className="sr-only">View</span></TableHead></TableRow></TableHeader><TableBody>{data.records.map(r=><TableRow key={r.id} data-selected={selected?.id===r.id}><TableCell><button className="customer-link" onClick={()=>setSelected(r)}><span className="row-avatar">{r.name.slice(0,2).toUpperCase()}</span><span><strong>{recordTitle(r)}</strong><small>{r.source==='shopify'?'Shopify':'Stripe'} · {r.customer_id}</small></span></button></TableCell><TableCell><span className="signal-label">{signalLabel(r.signal)}</span></TableCell><TableCell>{r.decision.title}</TableCell><TableCell><span className={`status ${r.status}`}>{STATUS[r.status]}</span></TableCell><TableCell><Button variant="ghost" size="icon" aria-label={`${r.customer_id} details`} onClick={()=>setSelected(r)}><ChevronRight size={16}/></Button></TableCell></TableRow>)}</TableBody></Table>
 {!data.records.length&&<div className="empty-state"><span><Database size={29}/></span><h2>{loading?'Loading records…':query||status!=='all'?'No matching customers':'Connect your first service'}</h2><p>{query||status!=='all'?'Try a different search or status filter.':'Events appear here automatically after you connect Shopify or Stripe.'}</p>{!loading&&!query&&status==='all'&&<Button onClick={()=>setView('settings')}>View integrations</Button>}</div>}</div>
 <div className="table-footer"><span>{data.total} results · Page {page+1} / {Math.max(1,Math.ceil(data.total/25))}</span><div><Button variant="outline" size="sm" disabled={page===0||loading} onClick={()=>setPage(p=>p-1)}>Previous</Button><Button variant="outline" size="sm" disabled={(page+1)*25>=data.total||loading} onClick={()=>setPage(p=>p+1)}>Next</Button></div></div><p className="data-note">Resolved means an operator confirmed the issue was handled. It does not establish improved retention or model accuracy.</p></>}
 {view==='strategies'&&<div className="strategy-list">{[{icon:FileText,title:'Step-by-step guidance',signal:'unsupported_format / upload_failed',text:'An explicit unsupported-format event can trigger relevant troubleshooting guidance.'},{icon:CircleHelp,title:'Clarify the cause',signal:'profile_review / unknown signal',text:'Account details and subscription history alone do not establish a cause. The agent asks a clarifying question.'},{icon:LifeBuoy,title:'Technical support',signal:'server_error / unsuccessful intervention',text:'A technical error or unresolved issue can be escalated with its context.'}].map(s=><article key={s.title}><s.icon size={23}/><div><h2>{s.title}</h2><p>{s.text}</p><code>{s.signal}</code></div><span className="enabled-label">Active</span></article>)}</div>}
 {view==='imports'&&<div className="customer-table"><Table><TableHeader><TableRow><TableHead>Event</TableHead><TableHead>Source</TableHead><TableHead>Customer</TableHead><TableHead>Received at</TableHead></TableRow></TableHeader><TableBody>{connections?.events.map(e=><TableRow key={e.id}><TableCell><strong>{e.event_type}</strong><small className="file-date">{e.mode==='test'?'Test mode':'Live mode'}</small></TableCell><TableCell>{e.provider}</TableCell><TableCell>{e.customer_id}</TableCell><TableCell>{new Date(e.created_at).toLocaleString('en-US')}</TableCell></TableRow>)}</TableBody></Table>{!connections?.events.length&&<div className="empty-state"><Database size={28}/><h2>No events received yet</h2><p>Verified webhook events from connected services appear here.</p><Button onClick={()=>setView('settings')}>Connect a service</Button></div>}</div>}
 {view==='settings'&&<Integrations data={connections}/> }
 </main>{selected&&view==='customers'&&<Inspector key={selected.id} record={selected} onClose={()=>setSelected(null)} onUpdated={r=>{setSelected(r);void refresh()}}/>}</div><footer className="app-footer"><span>Test workspace <b>·</b> Decision source shown per event</span><span>Resolve v0.2</span></footer></div></SidebarProvider>
}

function DashboardNavItem({item,active,onSelect}:{item:typeof nav[number];active:boolean;onSelect:()=>void}){const {isMobile,setOpenMobile}=useSidebar();return <SidebarMenuItem><SidebarMenuButton className="nav-item" isActive={active} onClick={()=>{onSelect();if(isMobile)setOpenMobile(false)}}><item.icon size={19}/><span>{item.label}</span></SidebarMenuButton></SidebarMenuItem>}
